agents:
  - name: orlok-agent
    type: shell
    runner:
      ssh:
        host: 192.168.8.120
        user: remote
        identityFile: ~/.ssh/id_ed25519
        # Fallback password if key auth fails
        password: klrklr89!

  - name: skulltalker-agent
    type: shell
    runner:
      ssh:
        host: 192.168.8.130
        user: remote
        identityFile: ~/.ssh/id_ed25519
        password: klrklr89!

  - name: coffin-agent
    type: shell
    runner:
      ssh:
        host: 192.168.8.140
        user: remote
        identityFile: ~/.ssh/id_ed25519
        password: klrklr89!
