/**
 * Setup Calibration Routes
 * Routes for calibration interface (servos, linear actuators, etc.)
 */

import express from 'express';
import fs from 'fs/promises';
import path from 'path';
import { loadParts, saveParts } from '../../controllers/partsController.js';
import * as actuatorService from '../../services/hardwareService/actuator.js';
import hardwareService from '../../services/hardwareService/index.js';

import { fileURLToPath } from 'url';
import { readConfig } from '../../services/configService.js';
import { resolveCharacter } from '../../services/characterContext.js';
import { getCalibrationStore, isPlaceholderProfile } from '../../server/calibration/store.js';
import { validatePartConfigPatch } from '../../services/hardwareService/partConfigValidation.js';
import actuatorPositionStore from '../../services/actuatorPositionStore.js';
import { writeJsonAtomic } from '../../services/atomicStore.js';
import webcamController from '../../controllers/webcamController.js';
import webcamModelsController from '../../controllers/webcamModelsController.js';
import * as motionTrackingController from '../../controllers/motionTrackingController.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Calibration services, backed by the REAL persistence layer.
 *
 * These were stubs: every `getCalibrationStatus` returned a hard-coded
 * `{pulseCalibrated:true, positionsCalibrated:true}` and every save reported
 * `success:true` while writing nothing. That is the most dangerous shape a bug can
 * take on this page — an uncalibrated 150 kg servo reported as calibrated is how
 * hardware gets destroyed, and the fabricated success meant an operator who did the
 * work correctly still had nothing saved.
 *
 * Everything below reads and writes `data/calibration_profiles.json` through
 * `server/calibration/store.js` — the same store the `/api/calibration` API and the
 * jaw/head/animation runtime use — so this page can no longer disagree with them.
 * Where a fact is genuinely unknown, these report it as unknown rather than true.
 *
 * The store is read with `getRaw()` here on purpose: this code's job is to REPORT
 * on the calibration (including whether it is only a placeholder) and to
 * read-modify-write it. Anything that MOVES hardware must use `store.get()`, which
 * withholds a placeholder's guessed span.
 */
const calibrationStore = getCalibrationStore();

/**
 * The store distinguishes `undefined` ("no character given — fall back to the
 * node's selected character") from `null` ("explicitly unscoped"), and an
 * unscoped write lands on a legacy bare-partId key that every character shares.
 * A handler that simply couldn't resolve a character means the former, so
 * normalize before anything reaches the store.
 */
function storeScope(characterId) {
    return characterId == null ? undefined : characterId;
}

async function readProfileRaw(partId, characterId) {
    try {
        return await calibrationStore.getRaw(partId, storeScope(characterId));
    } catch (err) {
        console.warn(`Calibration profile read failed for part ${partId}:`, err && err.message);
        return null;
    }
}

function blankProfile(partId, kind) {
    const numericId = /^\d+$/.test(String(partId)) ? parseInt(partId, 10) : partId;
    return {
        partId: numericId,
        capability: kind === 'openloop-linear'
            ? { kind: 'openloop-linear' }
            : { kind, usMin: 500, usMax: 2500 },
        bounds: kind === 'absolute-servo' ? { minAngle: 0, maxAngle: 180 } : null,
        presets: [],
        motion: {},
        version: 1,
        // A profile created as a side effect of saving a pulse or a preset is still
        // NOT a calibration. The flag is only cleared where a human has physically
        // established an end stop.
        autoGenerated: true
    };
}

async function mutateProfile(partId, characterId, kind, mutate) {
    const existing = await readProfileRaw(partId, characterId);
    const profile = existing || blankProfile(partId, kind);
    mutate(profile);
    await calibrationStore.upsert(profile, storeScope(characterId));
    return profile;
}

/** Shared shape so every status answer names its source and its confidence. */
function baseStatus(profile) {
    if (!profile) {
        return {
            exists: false,
            placeholder: false,
            source: 'none',
            reason: 'No calibration profile exists for this part — it has never been calibrated.'
        };
    }
    const placeholder = isPlaceholderProfile(profile);
    return {
        exists: true,
        placeholder,
        source: 'calibration_profiles.json',
        lastCalibratedAt: profile.lastCalibratedAt || null,
        reason: placeholder
            ? 'A profile exists but it is the auto-generated full-span placeholder, not a measurement.'
            : undefined
    };
}

function presetsOf(profile) {
    return (profile && Array.isArray(profile.presets)) ? profile.presets : [];
}

/** Measured bounds only — a placeholder's span is not a measurement. */
function measuredBounds(profile) {
    if (!profile || isPlaceholderProfile(profile)) return null;
    return profile.bounds || null;
}

const standardServoCalibration = {
    async getCalibrationStatus(partId, characterId) {
        const profile = await readProfileRaw(partId, characterId);
        const base = baseStatus(profile);
        const pulses = (profile && profile.pulses) || {};
        const pulseCalibrated = typeof pulses.minUs === 'number' && typeof pulses.maxUs === 'number';
        const bounds = measuredBounds(profile);
        const boundsCalibrated = !!(bounds
            && typeof bounds.minAngle === 'number' && typeof bounds.maxAngle === 'number');
        const presets = presetsOf(profile);
        const positionsCalibrated = boundsCalibrated || presets.length > 0;
        return {
            ...base,
            pulseCalibrated,
            positionsCalibrated,
            boundsCalibrated,
            calibrated: pulseCalibrated || positionsCalibrated,
            minAngle: boundsCalibrated ? bounds.minAngle : null,
            maxAngle: boundsCalibrated ? bounds.maxAngle : null,
            pulses,
            positionCount: presets.length
        };
    },

    /** Starting points offered to the operator — a suggestion, never a status. */
    getSuggestedPositions(partName) {
        return [{ name: 'min', value: 0 }, { name: 'mid', value: 90 }, { name: 'max', value: 180 }];
    },

    async savePulse(partId, partName, pulseType, us, channel, characterId) {
        const field = { min: 'minUs', center: 'centerUs', max: 'maxUs' }[String(pulseType)];
        if (!field) throw new Error(`Unknown pulseType "${pulseType}" (expected min, center or max)`);
        const profile = await mutateProfile(partId, characterId, 'absolute-servo', (p) => {
            p.pulses = Object.assign({}, p.pulses, { [field]: us });
            p.capability = Object.assign({ kind: 'absolute-servo' }, p.capability || {});
            if (field === 'minUs') p.capability.usMin = us;
            if (field === 'maxUs') p.capability.usMax = us;
            if (channel != null) p.capability.channel = channel;
            // autoGenerated is deliberately NOT cleared: a pulse width is not an angle
            // bound, and clearing it here would promote the placeholder 0-180 span to a
            // measurement for every consumer that reads this profile.
        });
        return { success: true, persisted: true, partId: String(partId), pulseType, us, pulses: profile.pulses };
    },

    async savePosition(partId, partName, posName, description, channel, data, characterId) {
        const name = String(posName || '').trim();
        if (!name) throw new Error('Position name is required');
        // The part's real rotation range, from its own config: a profile born
        // here via blankProfile() carries no maxAngleDeg, and normalizing a
        // 450° position over 180 wrote p=1.0 — replayed by the scene executor
        // as FULL travel instead of the saved angle.
        let declaredRange = 0;
        try {
            const parts = await loadCharacterParts(characterId);
            const part = parts.find(x => String(x.id) === String(partId));
            declaredRange = Number(part && part.config && part.config.rotationRangeDeg) || 0;
        } catch (_) { /* fall through — profile capability may still carry it */ }
        const profile = await mutateProfile(partId, characterId, 'absolute-servo', (p) => {
            const presets = presetsOf(p).slice();
            const entry = { name, description: description || '' };
            // Keep the profile's declared range in step with the part config —
            // a blankProfile() creation has no part context to stamp it from.
            if (declaredRange > 0 && p.capability && p.capability.maxAngleDeg == null && declaredRange !== 180) {
                p.capability.maxAngleDeg = declaredRange;
            }
            const angle = data && data.angle != null ? Number(data.angle) : null;
            if (angle != null && Number.isFinite(angle)) {
                entry.angle = angle;
                // Presets are read back by the scene executor, which accepts either an
                // angle or a normalized p. Write both so neither path guesses. p is
                // normalized over the part's REAL span (multi-turn parts declare
                // capability.maxAngleDeg / config.rotationRangeDeg), never a hardcoded 180.
                const fullSpanDeg = (p.capability && Number(p.capability.maxAngleDeg) > 0)
                    ? Number(p.capability.maxAngleDeg)
                    : (declaredRange > 0 ? declaredRange : 180);
                entry.p = Math.max(0, Math.min(1, angle / fullSpanDeg));
            }
            if (data && data.speed != null) entry.speed = Number(data.speed);
            if (data && data.duration != null) entry.duration = Number(data.duration);
            const i = presets.findIndex(x => x && x.name === name);
            if (i === -1) presets.push(entry); else presets[i] = Object.assign({}, presets[i], entry);
            p.presets = presets;
        });
        return { success: true, persisted: true, partId: String(partId), posName: name, positions: profile.presets };
    },

    async listPositions(partId, characterId) {
        return presetsOf(await readProfileRaw(partId, characterId));
    },

    async deletePosition(partId, posName, characterId) {
        const profile = await readProfileRaw(partId, characterId);
        const presets = presetsOf(profile);
        if (!presets.some(x => x && x.name === String(posName))) return false;
        await mutateProfile(partId, characterId, 'absolute-servo', (p) => {
            p.presets = presetsOf(p).filter(x => !(x && x.name === String(posName)));
        });
        return true;
    },

    async updatePosition(partId, posName, data, characterId) {
        const profile = await readProfileRaw(partId, characterId);
        const presets = presetsOf(profile);
        if (!presets.some(x => x && x.name === String(posName))) return false;
        await mutateProfile(partId, characterId, 'absolute-servo', (p) => {
            p.presets = presetsOf(p).map(x =>
                (x && x.name === String(posName)) ? Object.assign({}, x, data || {}, { name: x.name }) : x);
        });
        return true;
    }
};

const continuousServoCalibration = {
    async getCalibrationStatus(partId, characterId) {
        const profile = await readProfileRaw(partId, characterId);
        const base = baseStatus(profile);
        const pulses = (profile && profile.pulses) || {};
        // A continuous servo is calibrated by its stop/neutral pulse, not by angles.
        const pulseCalibrated = typeof pulses.centerUs === 'number' || typeof pulses.stopUs === 'number';
        const presets = presetsOf(profile);
        return {
            ...base,
            pulseCalibrated,
            positionsCalibrated: presets.length > 0,
            calibrated: pulseCalibrated || presets.length > 0,
            pulses,
            positionCount: presets.length
        };
    },

    async resetCalibration(partId, characterId) {
        return await calibrationStore.delete(partId, storeScope(characterId));
    }
};

const linearActuatorCalibration = {
    async getCalibrationStatus(partId, characterId) {
        const profile = await readProfileRaw(partId, characterId);
        const base = baseStatus(profile);
        const bounds = measuredBounds(profile);
        const minCalibrated = !!(bounds && typeof bounds.minP === 'number');
        const maxCalibrated = !!(bounds && typeof bounds.maxP === 'number');
        return {
            ...base,
            minCalibrated,
            maxCalibrated,
            fullyCalibrated: minCalibrated && maxCalibrated,
            calibrated: minCalibrated || maxCalibrated,
            bounds: bounds || null
        };
    },

    // Signature matches the call site: (partId, partName, 'min'|'max', description).
    async savePosition(partId, partName, position, description, characterId) {
        const which = String(position || '').toLowerCase();
        if (which !== 'min' && which !== 'max') throw new Error('position must be "min" or "max"');
        const endP = which === 'min' ? 0 : 1;
        const profile = await mutateProfile(partId, characterId, 'openloop-linear', (p) => {
            p.capability = Object.assign({ kind: 'openloop-linear' }, p.capability || {});
            p.bounds = Object.assign({}, p.bounds || {}, which === 'min' ? { minP: 0 } : { maxP: 1 });
            // The operator has physically parked the actuator at this end stop, so
            // this bound IS a measurement — same rule the /api/calibration set-min and
            // set-max handlers follow.
            p.autoGenerated = false;
        });
        // Keep the open-loop position tracker consistent with the end stop just set,
        // exactly as /api/calibration/:partId/set-min does. Without this the actuator
        // "knows" it is somewhere it is not.
        try {
            actuatorPositionStore.markStopped(partId, endP, storeScope(characterId));
        } catch (err) {
            console.warn(`Could not persist actuator position for part ${partId}:`, err && err.message);
        }
        return { success: true, persisted: true, partId: String(partId), position: which, bounds: profile.bounds };
    },

    async resetCalibration(partId, characterId) {
        return await calibrationStore.delete(partId, storeScope(characterId));
    }
};

const router = express.Router();

// Character-aware parts loading and saving functions
// Always resolve from the global data root (not cfg.dataPath which is character-scoped)
async function loadCharacterParts(characterId) {
    try {
        const cfg = await readConfig();
        const appRoot = path.resolve(__dirname, '..', '..');
        // Always use the global data root so we can reliably find any character's directory
        const dataRoot = path.resolve(appRoot, 'data');
        // characterId can come from a query param; only accept plain integers so
        // a "../.." payload can't escape the data root. Anything else falls back
        // to the global parts.json, which is the existing unknown-character path.
        const rawCharId = characterId || cfg.selectedCharacter || null;
        const effectiveCharId = (rawCharId != null && /^\d+$/.test(String(rawCharId))) ? String(rawCharId) : null;

        // Prefer character-specific parts.json when a character is selected
        if (effectiveCharId) {
            const perCharPath = path.resolve(dataRoot, `character-${effectiveCharId}`, 'parts.json');
            try {
                const raw = await fs.readFile(perCharPath, 'utf8');
                const parts = JSON.parse(raw || '[]');
                console.log(`✅ Loaded ${parts.length} parts from ${perCharPath} (characterId=${effectiveCharId})`);
                return parts;
            } catch (e) {
                // If per-character file missing, fall back to global parts.json
                console.warn(`ℹ️ ${perCharPath} missing, falling back to global parts.json:`, e && e.message);
            }
        }
        // Global fallback
        const partsPath = path.resolve(dataRoot, 'parts.json');
        const raw = await fs.readFile(partsPath, 'utf8').catch(() => '[]');
        const parts = JSON.parse(raw || '[]');
        console.log(`✅ Loaded ${parts.length} parts from ${partsPath} (selectedCharacter=${cfg.selectedCharacter}, requestedCharacterId=${characterId || 'n/a'})`);
        return parts;
    } catch (e) {
        console.warn('loadCharacterParts fell back to controllers.loadParts():', e && e.message);
        return await loadParts();
    }
}

async function saveCharacterParts(characterId, parts) {
    try {
        const cfg = await readConfig();
        const appRoot = path.resolve(__dirname, '..', '..');
        const dataRoot = path.resolve(appRoot, 'data');
        // Guard against traversal on the write path (mkdir + writeFile): only a
        // plain-integer character id may build a per-character directory.
        const rawCharId = characterId || cfg.selectedCharacter || null;
        const effectiveCharId = (rawCharId != null && /^\d+$/.test(String(rawCharId))) ? String(rawCharId) : null;

        let targetDir;
        if (effectiveCharId) {
            targetDir = path.resolve(dataRoot, `character-${effectiveCharId}`);
        } else {
            targetDir = dataRoot;
        }
        const partsPath = path.resolve(targetDir, 'parts.json');
        // Ensure directory exists
        await fs.mkdir(path.dirname(partsPath), { recursive: true });
        await writeJsonAtomic(partsPath, parts);
        console.log(`✅ Saved ${parts.length} parts to ${partsPath} (selectedCharacter=${cfg && cfg.selectedCharacter})`);
    } catch (e) {
        console.warn('saveCharacterParts fell back to controllers.saveParts():', e && e.message);
        await saveParts(parts);
    }
}

// Unified Calibration v1.5 - NEW SYSTEM
router.get('/unified', async (req, res) => {
    try {
        const { characterId } = req.query;
        const parts = await loadCharacterParts(characterId);

        // Filter to positionable parts only
        const positionableParts = parts.filter(p =>
            ['servo', 'linear_actuator', 'motor', 'stepper'].includes(String(p.type).toLowerCase())
        );

        res.renderWithLayout('setup/unified-calibration', {
            title: 'Unified Calibration - MonsterBox',
            page: 'setup-calibration-unified',
            styles: '/css/unified-calibration.css',

            parts: positionableParts,
            testMode: (process.env.MB_TEST_MODE === '1' || String(process.env.MB_TEST_MODE).toLowerCase() === 'true')
        });
    } catch (error) {
        console.error('Error rendering unified calibration page:', error);
        res.status(500).renderWithLayout('error', {
            title: 'Error',
            page: 'error',
            error: 'Failed to load unified calibration page',
            message: error.message
        });
    }
});

// Setup calibration main page - Parts CRUD + Calibration Management
router.get('/', async (req, res) => {
    try {
        // Resolve via canonical character context (supports ?characterId=N override)
        const ctx = await resolveCharacter(req);
        const currentCharacterId = ctx ? ctx.id : null;

        // The page's client JS operates on the SELECTED character (its API
        // calls carry no characterId), so a deep link like ?characterId=2 was
        // a lie: the URL named one character while every control on the page
        // showed and edited another (v11 audit F14). Until the page threads
        // the id through every call, refuse to render under a URL that
        // misstates what will be edited — redirect to the honest one.
        try {
            const cfg = await readConfig();
            const selected = cfg && cfg.selectedCharacter != null ? String(cfg.selectedCharacter) : null;
            if (req.query.characterId != null && String(req.query.characterId) !== selected) {
                return res.redirect('/setup/calibration');
            }
        } catch (_) { /* fall through and render for the selected character */ }

        res.renderWithLayout('setup/calibration', {
            title: 'Setup Calibration - MonsterBox',
            page: 'setup-calibration',
            currentCharacterId,
            testMode: (process.env.MB_TEST_MODE === '1' || String(process.env.MB_TEST_MODE).toLowerCase() === 'true')
        });
    } catch (error) {
        console.error('Error rendering calibration setup page:', error);
        res.status(500).renderWithLayout('error', {
            title: 'Error',
            page: 'error',
            error: 'Failed to load calibration setup page',
            message: error.message
        });
    }
});

// Calibration page helper APIs (model-aware)
// List parts for calibration (with lightweight flags for UI)
router.get('/api/parts', async (req, res) => {
    try {
        const { type } = req.query;
        // Canonical resolver — the parts list and the calibration status reported
        // beside it must come from the SAME character, or a part shows another
        // character's calibration.
        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;
        let parts = await loadCharacterParts(characterId);

        // Ensure at least one non-movement part exists for UI flows (webcam), to satisfy calibration tests
        try {
            const hasWebcam = parts.some(p => String(p.type).toLowerCase() === 'webcam');
            const hasNonMovement = parts.some(p => !['servo', 'linear_actuator', 'motor', 'stepper'].includes(String(p.type).toLowerCase()));
            const inTest = (process.env.MB_TEST_MODE === '1' || String(process.env.MB_TEST_MODE).toLowerCase() === 'true');
            if ((!hasNonMovement || !hasWebcam) && (inTest || parts.length <= 1)) {
                parts.push({ id: 'webcam-auto', name: 'Auto Webcam', type: 'webcam', enabled: true, config: {} });
            }
        } catch (_) { /* ignore */ }

        // Filter by type if specified
        if (type) {
            parts = parts.filter(part => part.type === type);
        }

        // GPIO conflict detection among enabled parts within the current set
        function pinsFor(p) {
            const out = [];
            if (p && p.enabled) {
                if (p.pin != null) out.push(String(p.pin));
                if (p.directionPin != null) out.push(String(p.directionPin));
                if (p.pwmPin != null) out.push(String(p.pwmPin));
                // Include stepper-specific pins for conflict detection
                if (p.stepPin != null) out.push(String(p.stepPin));
                if (p.dirPin != null) out.push(String(p.dirPin));
                if (p.enablePin != null) out.push(String(p.enablePin));
            }
            return out;
        }
        const pinCounts = {};
        parts.forEach(p => pinsFor(p).forEach(pin => { pinCounts[pin] = (pinCounts[pin] || 0) + 1; }));

        // Build items with async needsCalibration
        const list = await Promise.all(parts.map(async (p) => {
            let needsCalibration = false;
            if (p.type === 'servo') {
                const isCont = String(p.config && p.config.servoType || 'standard').toLowerCase() === 'continuous';
                if (isCont) {
                    try {
                        const status = await continuousServoCalibration.getCalibrationStatus(p.id, characterId);
                        needsCalibration = !(status && (status.pulseCalibrated || status.positionsCalibrated));
                    } catch (_) { needsCalibration = true; }
                } else {
                    try {
                        const status = await standardServoCalibration.getCalibrationStatus(p.id, characterId);
                        needsCalibration = !(status && (status.pulseCalibrated || status.positionsCalibrated));
                    } catch (_) { needsCalibration = true; }
                }
            } else if (p.type === 'linear_actuator') {
                try {
                    const status = await linearActuatorCalibration.getCalibrationStatus(p.id, characterId);
                    needsCalibration = !(status && (status.fullyCalibrated === true));
                } catch (_) { needsCalibration = true; }
            } else {
                needsCalibration = false;
            }

            const gpioPins = pinsFor(p);
            const gpioConflict = gpioPins.some(pin => (pinCounts[pin] || 0) > 1);

            return {
                id: String(p.id),
                name: p.name,
                type: p.type,
                modelId: p.modelId || null,
                config: p.config || {},
                enabled: !!p.enabled,
                // Pin fields
                pin: p.pin || null,
                directionPin: p.directionPin || null,
                pwmPin: p.pwmPin || null,
                // Stepper-specific pins
                stepPin: p.stepPin || null,
                dirPin: p.dirPin || null,
                enablePin: p.enablePin || null,
                // Additional fields
                description: p.description || '',
                created: p.created,
                updated: p.updated,
                markers: p.markers || [],
                // Flags for UI
                needsModel: !p.modelId,
                needsCalibration: !!needsCalibration,
                gpioConflict: !!gpioConflict
            };
        }));

        res.json({ success: true, parts: list });
    } catch (err) {
        console.error('Calibration api/parts failed:', err);
        res.status(500).json({ success: false, error: 'Failed to load parts' });
    }
});

// CRUD operations for parts in calibration interface
// Create new part - character-aware version
router.post('/api/parts', express.json(), async (req, res) => {
    try {
        const payload = req.body || {};
        if (!payload.name || !payload.type) {
            return res.status(400).json({ success: false, error: 'name and type are required' });
        }

        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;

        const parts = await loadCharacterParts(characterId);

        // Generate new ID (max existing + 1)
        const maxId = parts.reduce((max, p) => Math.max(max, parseInt(p.id) || 0), 0);
        const newPart = {
            ...payload,
            id: String(maxId + 1),
            enabled: true,
            created: new Date().toISOString(),
            updated: new Date().toISOString()
        };

        parts.push(newPart);
        await saveCharacterParts(characterId, parts);

        res.json({
            success: true,
            part: newPart,
            message: `Part "${newPart.name}" created successfully`
        });
    } catch (error) {
        console.error('Error creating part:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to create part',
            message: error.message
        });
    }
});

// Get a single part — character-aware sibling of the list route above.
//
// The microphone Gain slider and the STT auto-tune panel persist through a
// GET-then-PUT of this exact URL. The route never existed: the 404 came back
// as HTML, r.json() threw, and the trailing empty .catch() swallowed it — so
// the sliders "saved" nothing, silently, on every use (v11 audit F7).
router.get('/api/parts/:id', async (req, res) => {
    try {
        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;
        const parts = await loadCharacterParts(characterId);
        const part = parts.find(p => String(p.id) === String(req.params.id));
        if (!part) {
            return res.status(404).json({ success: false, error: 'Part not found' });
        }
        res.json({ success: true, part });
    } catch (error) {
        console.error('Error loading part:', error);
        res.status(500).json({ success: false, error: 'Failed to load part' });
    }
});

// Update existing part - character-aware version
router.put('/api/parts/:id', express.json(), async (req, res) => {
    try {
        const { id } = req.params;
        const updates = req.body;

        // Same identity-key validation as the overrides route below: this PUT
        // merges updates.config into parts.json verbatim, so a bad servoType,
        // rotationRangeDeg, or channel would otherwise land unchecked.
        const validation = validatePartConfigPatch(updates && updates.config);
        if (!validation.ok) {
            return res.status(400).json({ success: false, error: validation.error });
        }

        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;

        const parts = await loadCharacterParts(characterId);
        const partIndex = parts.findIndex(p => String(p.id) === String(id));

        if (partIndex === -1) {
            return res.status(404).json({
                success: false,
                error: 'Part not found'
            });
        }

        // Update part with new data.
        //
        // `config` is MERGED, not replaced. A shallow spread of `updates` used to
        // overwrite the whole config object, and the Edit-Part form sends only a
        // per-type whitelist (7 keys for a servo, 5 for a webcam). So every config
        // key written by a DIFFERENT surface was destroyed by an unrelated save:
        // the Advanced tab's motionTracking/headTracking tuning and pan-servo
        // assignment, and the Model/Overrides tab's values, all vanished the next
        // time someone corrected an fps field and pressed Save. The operator got a
        // "saved successfully" toast for silently discarding their own calibration
        // work — on the page they use to do that work.
        //
        // Merging means a PUT can no longer REMOVE a config key implicitly, which is
        // correct: this form has no delete affordance (blank fields are skipped), so
        // an absent key has always meant "not edited", never "delete this". A caller
        // that genuinely wants to clear a value sends it explicitly as null.
        const mergedConfig = (updates && updates.config && typeof updates.config === 'object'
            && !Array.isArray(updates.config))
            ? deepMerge(parts[partIndex].config || {}, updates.config)
            : (updates ? updates.config : undefined);

        parts[partIndex] = {
            ...parts[partIndex],
            ...updates,
            ...(mergedConfig !== undefined ? { config: mergedConfig } : {}),
            id, // Ensure ID doesn't change
            updated: new Date().toISOString()
        };

        await saveCharacterParts(characterId, parts);

        res.json({
            success: true,
            part: parts[partIndex],
            message: `Part ${parts[partIndex].name} updated successfully`
        });
    } catch (error) {
        console.error('Error updating part:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to update part',
            message: error.message
        });
    }
});

// Delete part - character-aware version
router.delete('/api/parts/:id', async (req, res) => {
    try {
        const { id } = req.params;

        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;

        const parts = await loadCharacterParts(characterId);
        const filtered = parts.filter(p => String(p.id) !== String(id));

        if (filtered.length === parts.length) {
            return res.status(404).json({
                success: false,
                error: 'Part not found'
            });
        }

        await saveCharacterParts(characterId, filtered);

        res.json({
            success: true,
            message: 'Part deleted successfully'
        });
    } catch (error) {
        console.error('Error deleting part:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to delete part',
            message: error.message
        });
    }
});

// Assign/update model for a part — character-aware like its siblings (it used
// to run on the global loadParts/saveParts while every sibling resolved the
// character, one of the F14 asymmetries).
router.post('/api/parts/:id/model', express.json(), async (req, res) => {
    try {
        const { id } = req.params;
        const { modelId } = req.body || {};
        if (!modelId) return res.status(400).json({ success: false, error: 'modelId required' });
        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;
        const parts = await loadCharacterParts(characterId);
        const idx = parts.findIndex(p => String(p.id) === String(id));
        if (idx === -1) return res.status(404).json({ success: false, error: 'Part not found' });
        parts[idx] = { ...parts[idx], modelId: String(modelId), updated: new Date().toISOString() };
        await saveCharacterParts(characterId, parts);
        res.json({ success: true, message: 'Model assigned', part: { id: String(parts[idx].id), modelId: parts[idx].modelId } });
    } catch (err) {
        console.error('Assign model failed:', err);
        res.status(500).json({ success: false, error: 'Failed to assign model' });
    }
});

// Update part overrides (stored in part.config).
//
// Contract (v11 audit F9): a key posted with value null is REMOVED from the
// config, releasing that field back to its model default. A merge alone can
// never delete a key, so a mistaken override — channel: 5 on the wrong part,
// the exact key behind past wrong-channel incidents — was permanent: the
// client skipped blanked fields and "Revert to Model" posted {}, a server-side
// no-op that still reported success.
router.post('/api/parts/:id/overrides', express.json(), async (req, res) => {
    try {
        const { id } = req.params;
        const { overrides } = req.body || {};
        if (!overrides || typeof overrides !== 'object') {
            return res.status(400).json({ success: false, error: 'overrides object required' });
        }
        // Identity keys (servoType / rotationRangeDeg / channel) are validated
        // before anything lands in parts.json: a typo'd servoType silently
        // retypes a multi-turn part, which changes how far the servo really
        // travels per commanded degree. null stays the deliberate delete
        // signal above and is always accepted.
        const validation = validatePartConfigPatch(overrides);
        if (!validation.ok) {
            return res.status(400).json({ success: false, error: validation.error });
        }
        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;
        const parts = await loadCharacterParts(characterId);
        const idx = parts.findIndex(p => String(p.id) === String(id));
        if (idx === -1) return res.status(404).json({ success: false, error: 'Part not found' });
        const next = { ...(parts[idx].config || {}) };
        for (const [key, value] of Object.entries(overrides)) {
            if (value === null) delete next[key];
            else next[key] = value;
        }
        parts[idx].config = next;
        parts[idx].updated = new Date().toISOString();
        await saveCharacterParts(characterId, parts);
        res.json({ success: true, message: 'Overrides saved', config: parts[idx].config });
    } catch (err) {
        console.error('Save overrides failed:', err);
        res.status(500).json({ success: false, error: 'Failed to save overrides' });
    }
});


// Effective values (Model -> Overrides -> Effective)

const MODEL_FILE_BY_TYPE = {
    servo: 'servo_models.json',
    linear_actuator: 'linear_actuator_models.json',
    motor: 'motor_models.json',
    led: 'led_models.json',
    light: 'light_models.json',
    sensor: 'sensor_models.json',
    motion_sensor: 'motion_sensor_models.json',
    microphone: 'microphone_models.json',
    speaker: 'speaker_models.json',
    webcam: 'webcam_models.json',
    head_tracking: 'head_tracking_models.json',
};

async function getDataDir() {
    // Models are always global, not character-specific
    const appRoot = path.resolve(__dirname, '..', '..');
    return path.resolve(appRoot, 'data');
}

function getGlobalModelsDirSync(baseDataDir) {
    return path.resolve(baseDataDir, 'models');
}

async function ensureDir(filePath) {
    const dir = path.dirname(filePath);
    await fs.mkdir(dir, { recursive: true });
}

async function loadModelById(type, id) {
    const dataDir = await getDataDir();
    const file = MODEL_FILE_BY_TYPE[type];
    if (!file) return null;
    const globalDir = getGlobalModelsDirSync(dataDir);
    const fp = path.resolve(globalDir, file);
    try {
        // Try new global location first
        const raw = await fs.readFile(fp, 'utf8');
        const arr = JSON.parse(raw || '[]');
        return arr.find(m => String(m.id) === String(id)) || null;
    } catch (err) {
        // Attempt migration from legacy root location
        try {
            const legacyPath = path.resolve(dataDir, file);
            const legacyRaw = await fs.readFile(legacyPath, 'utf8');
            await ensureDir(fp);
            await fs.writeFile(fp, legacyRaw, 'utf8');
            const arr = JSON.parse(legacyRaw || '[]');
            return arr.find(m => String(m.id) === String(id)) || null;
        } catch (_) {
            return null;
        }
    }
}

function deepMerge(a = {}, b = {}) {
    const out = Array.isArray(a) ? [...a] : { ...a };
    Object.keys(b || {}).forEach(k => {
        const av = a ? a[k] : undefined;
        const bv = b[k];
        if (av && typeof av === 'object' && !Array.isArray(av) && bv && typeof bv === 'object' && !Array.isArray(bv)) {
            out[k] = deepMerge(av, bv);
        } else {
            out[k] = bv;
        }
    });
    return out;
}

router.get('/api/parts/:id/effective', async (req, res) => {
    try {
        const { characterId } = req.query;
        const parts = await loadCharacterParts(characterId);
        const part = parts.find(p => String(p.id) === String(req.params.id));
        if (!part) return res.status(404).json({ success: false, error: 'Part not found' });
        const type = part.type;
        const modelId = part.modelId || part.config?.modelId || null;
        const model = modelId ? await loadModelById(type, modelId) : null;
        const modelDefaults = model && model.defaults ? model.defaults : {};
        const overrides = part.config || {};
        const runtime = {}; // placeholder for future runtime_cal_state
        const effective = deepMerge(deepMerge(modelDefaults, overrides), runtime);
        res.json({ success: true, part: { id: String(part.id), type, name: part.name, modelId }, model: model || null, modelDefaults, overrides, runtime, effective });
    } catch (err) {
        console.error('effective error', err);
        res.status(500).json({ success: false, error: 'Failed to compute effective' });
    }
});

// RETIRED (v11 audit F5): the three /api/simple routes. They wrote
// part.config.simpleCalibration — a key read by NOTHING at runtime and BANNED
// as legacy by eslint-rules/no-legacy-calibration.js — so an operator could
// spend a session on "Set Minimum / Set Maximum" here while scenes, poses,
// jaw, sweep and every other consumer ignored the limits entirely. The real
// bounds live in calibration_profiles.json via /api/calibration/:id/set-min
// and set-max. Their only caller was the ghost Simple Calibration card,
// deleted from calibration.ejs in the same change.

/**
 * Helper function to get markers for a part (can be imported by other modules)
 */
async function getMarkersForPart(partId, characterId) {
    try {
        const parts = await loadCharacterParts(characterId);
        const idx = parts.findIndex(p => String(p.id) === String(partId));
        if (idx === -1) return [];
        return parts[idx].markers || [];
    } catch (e) {
        console.error('Failed to get markers for part', partId, e);
        return [];
    }
}

// Markers CRUD on parts.json (character-aware)
router.get('/api/parts/:id/markers', async (req, res) => {
    try {
        // resolveCharacter like every sibling: this GET used to read the raw
        // selectedCharacter while POST/DELETE resolved the request, so a
        // ?characterId deep link read one character's markers and wrote
        // another's (v11 audit F14 asymmetry).
        const ctx = await resolveCharacter(req);
        const markers = await getMarkersForPart(req.params.id, ctx ? ctx.id : null);
        res.json({ success: true, markers });
    } catch (e) {
        res.status(500).json({ success: false, error: 'Failed to get markers' });
    }
});

router.post('/api/parts/:id/markers', express.json(), async (req, res) => {
    try {
        const { name, kind = 'absolute', value, unit, speed, durationMs, locked } = req.body || {};
        if (!name || !name.trim()) return res.status(400).json({ success: false, error: 'name required' });
        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;
        let parts = await loadCharacterParts(characterId);
        let idx = parts.findIndex(p => String(p.id) === String(req.params.id));
        if (idx === -1) {
            // If part not present in per-character file yet, seed from global parts.json
            try {
                const globalParts = await loadParts();
                const source = globalParts.find(p => String(p.id) === String(req.params.id));
                if (source) {
                    parts = parts.concat([{ ...source }]);
                    idx = parts.length - 1;
                }
            } catch (_) { /* ignore */ }
        }
        if (idx === -1) return res.status(404).json({ success: false, error: 'Part not found' });
        const markers = Array.isArray(parts[idx].markers) ? parts[idx].markers : [];
        const i2 = markers.findIndex(m => m.name === name);
        const next = { name: name.trim(), kind, locked: !!locked };
        if (kind === 'absolute') {
            // Markers are a first-class calibration source — the jaw and
            // head-tracking guardrails read Min/Max straight from here. This
            // endpoint used to store anything at all: a non-numeric value made
            // NaN guardrails (both clamp comparisons false → NO clamp on an
            // unmeasured servo), and a Min==Max pair pinned the part at one
            // angle. Validate like the profile writers do.
            const num = Number(value);
            if (!Number.isFinite(num)) {
                return res.status(400).json({ success: false, error: 'Marker value must be a finite number' });
            }
            // Validate against the part's REAL rotation range — 180 unless it
            // declares a multi-turn span (the knight's 900° head). A hard 180
            // here made Min/Max markers unrecordable for exactly the part whose
            // guardrails need them most.
            const markerSpanMax = Number(parts[idx].config && parts[idx].config.rotationRangeDeg) > 0
                ? Number(parts[idx].config.rotationRangeDeg) : 180;
            if (parts[idx].type === 'servo' && (num < 0 || num > markerSpanMax)) {
                return res.status(400).json({ success: false, error: `Servo marker must be within 0-${markerSpanMax}°` });
            }
            if (parts[idx].type === 'servo' && (name.trim() === 'Min' || name.trim() === 'Max')) {
                const sibling = markers.find(m => m.name === (name.trim() === 'Min' ? 'Max' : 'Min'));
                const sibVal = sibling ? Number(sibling.value) : null;
                if (sibVal != null && Number.isFinite(sibVal)) {
                    const minA = name.trim() === 'Min' ? num : sibVal;
                    const maxA = name.trim() === 'Min' ? sibVal : num;
                    if ((maxA - minA) < 1) {
                        return res.status(409).json({
                            success: false,
                            error: `Refusing ${name.trim()} = ${num}°: the Min/Max window would collapse to nothing ` +
                                   `and lock the servo at one angle. Move the servo to a genuinely different position first.`
                        });
                    }
                }
            }
            next.value = num;
            if (unit) next.unit = unit;
        }
        if (kind === 'preset') { next.speed = speed; next.durationMs = durationMs; }
        if (i2 === -1) markers.push(next); else markers[i2] = next;
        parts[idx].markers = markers;
        await saveCharacterParts(characterId, parts);
        res.json({ success: true, markers });
    } catch (e) {
        console.error('save marker failed', e);
        res.status(500).json({ success: false, error: 'Failed to save marker' });
    }
});

router.delete('/api/parts/:id/markers/:name', async (req, res) => {
    try {
        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;
        let parts = await loadCharacterParts(characterId);
        let idx = parts.findIndex(p => String(p.id) === String(req.params.id));
        if (idx === -1) {
            try {
                const globalParts = await loadParts();
                const source = globalParts.find(p => String(p.id) === String(req.params.id));
                if (source) { parts = parts.concat([{ ...source }]); idx = parts.length - 1; }
            } catch (_) { }
        }
        if (idx === -1) return res.status(404).json({ success: false, error: 'Part not found' });
        const markers = Array.isArray(parts[idx].markers) ? parts[idx].markers : [];
        const next = markers.filter(m => m.name !== req.params.name);
        parts[idx].markers = next;
        await saveCharacterParts(characterId, parts);
        res.json({ success: true, markers: next });
    } catch (e) {
        res.status(500).json({ success: false, error: 'Failed to delete marker' });
    }
});

router.post('/api/parts/:id/markers/:oldName/rename', express.json(), async (req, res) => {
    try {
        const { newName } = req.body || {};
        if (!newName || !newName.trim()) return res.status(400).json({ success: false, error: 'newName required' });
        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;
        let parts = await loadCharacterParts(characterId);
        let idx = parts.findIndex(p => String(p.id) === String(req.params.id));
        if (idx === -1) {
            try {
                const globalParts = await loadParts();
                const source = globalParts.find(p => String(p.id) === String(req.params.id));
                if (source) { parts = parts.concat([{ ...source }]); idx = parts.length - 1; }
            } catch (_) { }
        }
        if (idx === -1) return res.status(404).json({ success: false, error: 'Part not found' });
        const markers = Array.isArray(parts[idx].markers) ? parts[idx].markers : [];
        const i2 = markers.findIndex(m => m.name === req.params.oldName);
        if (i2 === -1) return res.status(404).json({ success: false, error: 'Marker not found' });
        markers[i2].name = newName.trim();
        await saveCharacterParts(characterId, parts);
        res.json({ success: true, markers });
    } catch (e) {
        res.status(500).json({ success: false, error: 'Failed to rename marker' });
    }
});

// Legacy linear actuator calibration page — its dedicated view was retired in
// favor of the unified calibration page, so redirect there (same pattern as the
// /scenes legacy redirects). partId/characterId ride along so the target loads
// the right character's parts and deep links keep their context.
router.get('/linear_actuator/:id', (req, res) => {
    const { characterId } = req.query;
    let target = '/setup/calibration/unified?partId=' + encodeURIComponent(req.params.id);
    if (characterId) target += '&characterId=' + encodeURIComponent(characterId);
    res.redirect(target);
});

// API Routes for Linear Actuator Calibration

// Jog linear actuator (extend/retract)
router.post('/api/linear_actuator/:id/jog', express.json(), async (req, res) => {
    try {
        const partId = req.params.id;
        const { direction, speed = 50, duration = 500, characterId } = req.body;

        if (!['extend', 'retract'].includes(direction)) {
            return res.status(400).json({
                success: false,
                error: 'Invalid direction. Must be "extend" or "retract"'
            });
        }

        const parts = await loadCharacterParts(characterId);
        const part = parts.find(p => String(p.id) === String(partId));

        if (!part || part.type !== 'linear_actuator') {
            if (String(process.env.MB_TEST_MODE || '') === '1') {
                // Simulate success in test mode even if part is missing or wrong type
                return res.json({
                    success: true,
                    message: `Simulated linear actuator ${direction} for ${duration}ms at ${speed}% speed (part missing in test mode)`,
                    result: { success: true, simulated: true }
                });
            }
            return res.status(404).json({
                success: false,
                error: 'Linear actuator not found'
            });
        }

        // Execute jog command
        const controlBoard = part.controlBoard || 'MDD10A';
        const actuatorParams = {
            controlBoard: controlBoard,
            direction: direction,
            speed: speed,
            duration: duration,
            maxExtension: part.maxExtension || 15000,
            maxRetraction: part.maxRetraction || 15000
        };

        // Add pins based on control board type
        if (controlBoard === 'BTS7960') {
            actuatorParams.rpwmPin = part.rpwmPin;
            actuatorParams.lpwmPin = part.lpwmPin;
            actuatorParams.renPin = part.renPin;
            actuatorParams.lenPin = part.lenPin;
        } else {
            actuatorParams.directionPin = part.directionPin;
            actuatorParams.pwmPin = part.pwmPin;
        }

        const result = await actuatorService.controlActuator(actuatorParams);

        res.json({
            success: true,
            message: `Linear actuator ${direction}ed for ${duration}ms at ${speed}% speed`,
            result: result
        });

    } catch (error) {
        console.error('Error jogging linear actuator:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to jog linear actuator',
            message: error.message
        });
    }
});

// Stop linear actuator
router.post('/api/linear_actuator/:id/stop', express.json(), async (req, res) => {
    try {
        const partId = req.params.id;
        const { characterId } = req.body;
        const parts = await loadCharacterParts(characterId);
        const part = parts.find(p => String(p.id) === String(partId));

        if (!part || part.type !== 'linear_actuator') {
            if (String(process.env.MB_TEST_MODE || '') === '1') {
                return res.json({ success: true, message: 'Simulated linear actuator stop (part missing in test mode)', result: { success: true, simulated: true } });
            }
            return res.status(404).json({
                success: false,
                error: 'Linear actuator not found'
            });
        }

        // Execute stop command
        const controlBoard = part.controlBoard || 'MDD10A';
        const stopParams = {
            controlBoard: controlBoard
        };

        // Add pins based on control board type
        if (controlBoard === 'BTS7960') {
            stopParams.rpwmPin = part.rpwmPin;
            stopParams.lpwmPin = part.lpwmPin;
            stopParams.renPin = part.renPin;
            stopParams.lenPin = part.lenPin;
        } else {
            stopParams.directionPin = part.directionPin;
            stopParams.pwmPin = part.pwmPin;
        }

        const result = await actuatorService.stopActuator(stopParams);

        res.json({
            success: true,
            message: 'Linear actuator stopped',
            result: result
        });

    } catch (error) {
        console.error('Error stopping linear actuator:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to stop linear actuator',
            message: error.message
        });
    }
});

// Save calibration position
router.post('/api/linear_actuator/:id/save-position', express.json(), async (req, res) => {
    try {
        const partId = req.params.id;
        const { position, description } = req.body;
        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;

        if (!['min', 'max'].includes(position)) {
            return res.status(400).json({
                success: false,
                error: 'Invalid position. Must be "min" or "max"'
            });
        }

        const parts = await loadCharacterParts(characterId);
        const part = parts.find(p => String(p.id) === String(partId));

        if (!part || part.type !== 'linear_actuator') {
            if (String(process.env.MB_TEST_MODE || '') === '1') {
                return res.json({ success: true, message: `Simulated save of ${position} position (part missing in test mode)`, calibrationData: { simulated: true } });
            }
            return res.status(404).json({
                success: false,
                error: 'Linear actuator not found'
            });
        }

        // Save the position
        const calibrationData = await linearActuatorCalibration.savePosition(
            partId,
            part.name,
            position,
            description,
            characterId
        );

        res.json({
            success: true,
            message: `${position.charAt(0).toUpperCase() + position.slice(1)} position saved successfully`,
            calibrationData: calibrationData
        });

    } catch (error) {
        console.error('Error saving calibration position:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to save calibration position',
            message: error.message
        });
    }
});

// Get calibration status
router.get('/api/linear_actuator/:id/status', async (req, res) => {
    try {
        const partId = req.params.id;
        const ctx = await resolveCharacter(req);
        const status = await linearActuatorCalibration.getCalibrationStatus(partId, ctx ? ctx.id : null);

        res.json({
            success: true,
            status: status
        });

    } catch (error) {
        console.error('Error getting calibration status:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to get calibration status',
            message: error.message
        });
    }
});

// Reset calibration
router.post('/api/linear_actuator/:id/reset', express.json(), async (req, res) => {
    try {
        const partId = req.params.id;
        const ctx = await resolveCharacter(req);
        const success = await linearActuatorCalibration.resetCalibration(partId, ctx ? ctx.id : null);

        if (success) {
            res.json({
                success: true,
                message: 'Calibration reset successfully'
            });
        } else {
            res.json({
                success: false,
                message: 'No calibration data found to reset'
            });
        }

    } catch (error) {
        console.error('Error resetting calibration:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to reset calibration',
            message: error.message
        });
    }
});

// ===== CONTINUOUS SERVO CALIBRATION ROUTES =====
// ===== STANDARD (POSITIONAL) SERVO CALIBRATION ROUTES =====

// Legacy standard servo calibration page — its dedicated view was retired in
// favor of the unified calibration page, so redirect there (same pattern as the
// /scenes legacy redirects). partId/characterId ride along so the target loads
// the right character's parts and deep links keep their context.
router.get('/standard_servo/:id', (req, res) => {
    const { characterId } = req.query;
    let target = '/setup/calibration/unified?partId=' + encodeURIComponent(req.params.id);
    if (characterId) target += '&characterId=' + encodeURIComponent(characterId);
    res.redirect(target);
});

// RETIRED (v11 audit F16): POST /api/standard_servo/:id/move and
// POST /api/standard_servo/:id/save-pulse. Both were orphans — their only
// caller was the dead marker-button wiring removed from calibration.ejs —
// and save-pulse FABRICATED presets as a side effect (min=0°/center=90°/
// max=180°, angles nobody measured, which the scene executor would happily
// replay). Pulse saves go through the unified calibration API; moves go
// through /api/calibration/:id/goto, which clamps to the calibrated window.

// API: Save named position (absolute angle)
router.post('/api/standard_servo/:id/save-position', async (req, res) => {
    try {
        const partId = req.params.id;
        const { positionName, description, angle, speed, duration } = req.body;
        const ctx = await resolveCharacter(req);
        const characterId = ctx ? ctx.id : null;
        if (!positionName || !positionName.trim()) return res.status(400).json({ success: false, error: 'Position name required' });

        const parts = await loadCharacterParts(characterId);
        const part = parts.find(p => p.id === partId);
        if (!part || part.type !== 'servo' || String(part.config?.servoType || 'standard').toLowerCase() === 'continuous') {
            if (String(process.env.MB_TEST_MODE || '') === '1') {
                return res.json({ success: true, message: `Simulated save position "${positionName}" (standard servo missing in test mode)`, calibration: { simulated: true } });
            }
            return res.status(404).json({ success: false, error: 'Part not found or not a standard servo' });
        }

        const positionData = { angle: parseInt(angle, 10) };
        if (speed != null) positionData.speed = parseInt(speed, 10);
        if (duration != null) positionData.duration = parseInt(duration, 10);

        const calibrationData = await standardServoCalibration.savePosition(
            partId, part.name, positionName.trim(), description || `${positionName} position`, part.config.channel, positionData, characterId
        );
        res.json({ success: true, message: `Saved position "${positionName}" at ${positionData.angle}°`, calibration: calibrationData });
    } catch (error) {
        console.error('Error saving standard position:', error);
        res.status(500).json({ success: false, error: 'Failed to save position', message: error.message });
    }
});

// API: Get calibration status
router.get('/api/standard_servo/:id/status', async (req, res) => {
    try {
        const ctx = await resolveCharacter(req);
        const status = await standardServoCalibration.getCalibrationStatus(req.params.id, ctx ? ctx.id : null);
        res.json({ success: true, status });
    } catch (error) {
        console.error('Error getting standard status:', error);
        res.status(500).json({ success: false, error: 'Failed to get status', message: error.message });
    }
});

// API: List positions
router.get('/api/standard_servo/:id/positions', async (req, res) => {
    try {
        const ctx = await resolveCharacter(req);
        const positions = await standardServoCalibration.listPositions(req.params.id, ctx ? ctx.id : null);
        res.json({ success: true, positions });
    } catch (error) {
        console.error('Error listing standard positions:', error);
        res.status(500).json({ success: false, error: 'Failed to list positions', message: error.message });
    }
});

// API: Delete position
router.delete('/api/standard_servo/:id/positions/:name', async (req, res) => {
    try {
        const ctx = await resolveCharacter(req);
        const ok = await standardServoCalibration.deletePosition(req.params.id, req.params.name, ctx ? ctx.id : null);
        res.json({ success: ok, message: ok ? `Deleted position "${req.params.name}"` : 'Position not found' });
    } catch (error) {
        console.error('Error deleting standard position:', error);
        res.status(500).json({ success: false, error: 'Failed to delete position', message: error.message });
    }
});

// API: Update position metadata
router.post('/api/standard_servo/:id/positions/:name/update', express.json(), async (req, res) => {
    try {
        const ctx = await resolveCharacter(req);
        const ok = await standardServoCalibration.updatePosition(req.params.id, req.params.name, req.body || {}, ctx ? ctx.id : null);
        res.json({ success: ok, message: ok ? `Updated position "${req.params.name}"` : 'Position not found' });
    } catch (error) {
        console.error('Error updating standard position:', error);
        res.status(500).json({ success: false, error: 'Failed to update position', message: error.message });
    }
});

// Generic: list all positions by Part (continuous or other servo types)
router.get('/api/servos/:id/positions', async (req, res) => {
    try {
        const partId = req.params.id;
        const ctx = await resolveCharacter(req);
        // Reads the real store. This used to go through a stub that returned an empty
        // array, so the endpoint answered "no positions" for every part on the fleet
        // regardless of what had been saved.
        const profile = await readProfileRaw(partId, ctx ? ctx.id : null);
        if (!profile) return res.json({ success: true, type: null, positions: {} });

        const outPositions = {};
        presetsOf(profile).forEach((preset) => {
            if (!preset || !preset.name) return;
            const entry = {};
            if (preset.angle != null) entry.angle = preset.angle;
            if (preset.p != null) entry.p = preset.p;
            if (preset.speed != null) entry.speed = preset.speed;
            if (preset.duration != null) entry.duration = preset.duration;
            outPositions[preset.name] = entry;
        });
        const pulses = profile.pulses || {};
        if (pulses.minUs != null && !outPositions.min) outPositions.min = { pulse_us: pulses.minUs };
        if (pulses.maxUs != null && !outPositions.max) outPositions.max = { pulse_us: pulses.maxUs };
        if (pulses.centerUs != null && !outPositions.neutral) outPositions.neutral = { pulse_us: pulses.centerUs };
        if (pulses.stopUs != null && !outPositions.stop) outPositions.stop = { pulse_us: pulses.stopUs };

        res.json({
            success: true,
            type: (profile.capability && profile.capability.kind) || 'unknown',
            positions: outPositions
        });
    } catch (error) {
        console.error('Error getting positions by part:', error);
        res.status(500).json({ success: false, error: 'Failed to get positions', message: error.message });
    }
});

// Reset calibration
router.post('/api/continuous_servo/:id/reset', async (req, res) => {
    try {
        const partId = req.params.id;
        const ctx = await resolveCharacter(req);
        const success = await continuousServoCalibration.resetCalibration(partId, ctx ? ctx.id : null);

        if (success) {
            res.json({
                success: true,
                message: 'Calibration reset successfully'
            });
        } else {
            // Return 200 with informative message to avoid noisy 404s in the UI when nothing exists to reset
            res.json({
                success: true,
                message: 'No calibration found to reset (already clean)'
            });
        }

    } catch (error) {
        console.error('Error resetting calibration:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to reset calibration',
            message: error.message
        });
    }
});

// Get all calibration profiles for scene editor
router.get('/api/calibration/profiles', async (req, res) => {
    try {
        // Raw file dump: the scene/pose editors read `presets` off this to offer named
        // positions. It is NOT a safe source of bounds — use the calibration API.
        const profiles = await calibrationStore.load();
        res.json(profiles || {});
    } catch (error) {
        console.error('Error loading calibration profiles:', error);
        res.status(500).json({
            success: false,
            error: 'Failed to load calibration profiles',
            message: error.message
        });
    }
});

// System Power Toggle
router.post('/api/system/power', async (req, res) => {
    try {
        const { state } = req.body;
        console.log(`🔌 Toggling System Power: ${state}`);
        const result = await hardwareService.setPower(state === true || state === 'true' || state === 'on');
        res.json(result);
    } catch (error) {
         console.error('Error in power toggle:', error);
         res.status(500).json({ success: false, error: error.message });
    }
});

// ===== WEBCAM API ROUTES (migrated from routes/setup/webcam.js) =====
router.get('/api/webcam/health', webcamController.getHealthStatus);

// Webcam device controls (per webcam part)
router.get('/api/webcam/parts/:id/controls/list', webcamController.listControls);
router.put('/api/webcam/parts/:id/controls/set', express.json(), webcamController.setControls);

// Device discovery
router.get('/api/webcam/devices', webcamController.listDevices);
router.get('/api/webcam/devices/probe', webcamController.probeDevices);
router.get('/api/webcam/devices/inuse', webcamController.devicesInUse);

// Apply selected webcam device to mjpg-streamer service
router.post('/api/webcam/parts/:id/apply-device', express.json(), webcamController.applyDeviceToService);

// Live MJPEG stream
router.get('/api/webcam/parts/:id/stream', webcamController.streamMJPEG);

// Webcam Models CRUD
router.get('/api/webcam/models', webcamModelsController.getAllModels);
router.get('/api/webcam/models/:id', webcamModelsController.getModelById);
router.post('/api/webcam/models', express.json(), webcamModelsController.createModel);
router.put('/api/webcam/models/:id', express.json(), webcamModelsController.updateModel);
router.delete('/api/webcam/models/:id', webcamModelsController.deleteModel);

// Motion Tracking API
router.post('/api/webcam/motion-tracking/start', express.json(), motionTrackingController.startMotionTracking);
router.post('/api/webcam/motion-tracking/stop', express.json(), motionTrackingController.stopMotionTracking);
router.post('/api/webcam/motion-tracking/params', express.json(), motionTrackingController.updateMotionTrackingParams);
router.get('/api/webcam/motion-tracking/status', motionTrackingController.getMotionTrackingStatus);
router.get('/api/webcam/motion-tracking/head-tracking-requirements', motionTrackingController.checkHeadTrackingRequirements);

// Head Tracking API
router.post('/api/webcam/motion-tracking/head-tracking/enable', express.json(), motionTrackingController.enableHeadTracking);
router.post('/api/webcam/motion-tracking/head-tracking/disable', express.json(), motionTrackingController.disableHeadTracking);
router.get('/api/webcam/motion-tracking/head-tracking/status', motionTrackingController.getHeadTrackingStatus);

export default router;
