// Global test setup file
// This runs before any tests to ensure the environment is correctly configured

import fs from 'fs';
import os from 'os';
import path from 'path';

// Set dummy API key to prevent ElevenLabs service from crashing during initialization
process.env.ELEVENLABS_API_KEY = 'test-dummy-key';

// Ensure other critical environment variables are set for testing
process.env.NODE_ENV = 'test';

/**
 * Sandbox the calibration store for the whole run.
 *
 * On a live animatronic node, data/calibration_profiles.json is the ONLY record
 * of a part's measured travel. It is untracked on purpose (v8.1.4, to stop
 * per-node part-ID collisions), so when it is lost, git cannot bring it back and
 * neither can anything else — the travel has to be re-measured by hand, part by
 * part, with the operator watching the hardware.
 *
 * A dozen unit tests inject synthetic parts and drive the real calibration
 * endpoints, which rewrite bounds. They protect the node by snapshotting the file
 * in before() and writing it back in after(). That protection only holds when
 * after() runs. Ctrl-C, a mocha timeout, an OOM on a Pi, or the suite being killed
 * all skip it, and whatever the test left behind becomes the node's calibration.
 *
 * That is what happened to Mina on 2026-09-12: the file came out holding six
 * autoGenerated placeholders. The jaw had lost its measured 28-84° window, so
 * commands drove it past its mechanical stop; the neck had lost
 * capability.invert and its 48-180° window, so every angle drove to the mirror
 * image, into the opposite stop. Three other characters' profiles were gone.
 * Both read as dead hardware.
 *
 * So the tests no longer get the chance. They run against a throwaway COPY, seeded
 * with the node's real content so anything asserting on real calibration still
 * sees it. However the run dies, the node's file is untouched.
 */
function sandboxCalibrationStore() {
  // An explicit override wins — a caller who set this knows what they want.
  if (process.env.MB_CALIBRATION_FILE) return;

  const live = path.resolve(process.cwd(), 'data/calibration_profiles.json');
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'mb-cal-'));
  const sandbox = path.join(dir, 'calibration_profiles.json');

  try {
    fs.copyFileSync(live, sandbox);
  } catch (err) {
    // No live file yet (a fresh checkout, or CI): an empty store is the correct
    // starting point, and the tests auto-create what they need.
    if (err.code !== 'ENOENT') throw err;
    fs.writeFileSync(sandbox, '{}', 'utf8');
  }

  process.env.MB_CALIBRATION_FILE = sandbox;
  console.log(`Calibration store sandboxed for this run: ${sandbox}`);
}

sandboxCalibrationStore();

console.log('Global test setup loaded: Environment variables configured.');
