[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
req_extensions = v3_req

[dn]
C=US
ST=Development
L=MonsterBox
O=MonsterBox Animatronics
OU=Development
CN=coffin.monsterbox.local

[v3_req]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = coffin
DNS.2 = coffin.local
DNS.3 = coffin.monsterbox.local
DNS.4 = localhost
IP.1 = 192.168.8.140
IP.2 = 127.0.0.1
IP.3 = ::1
