/**
 * Pose Health — classify every pose as `ok`, `degraded` or `blocked` at load time.
 *
 * The problem this solves: a pose whose parts are quarantined or physically dead
 * is still selectable, still reports "played", and silently does nothing. The
 * operator sees a pose list where every entry looks equally real. Health is
 * computed from the same committed source the hardware layer enforces
 * (`config/hardware-safety.json`, via services/hardwareService/safetyLimits.js)
 * plus the character's own parts.json, so it cannot drift from what will actually
 * happen when the pose runs.
 *
 *   blocked  — the pose cannot perform as authored. Some part is quarantined
 *              (`blockAllMotion`), its retract-block would refuse the authored
 *              direction, or the part does not exist for this character at all.
 *              Blocked poses are excluded from idle selection automatically.
 *   degraded — the pose will run, but not exactly as authored: an angle that will
 *              be clamped, a speed or duration that will be capped, a part on a
 *              serialized fused rail, a part whose only "calibration" is an
 *              autoGenerated placeholder, or a part the operator has disabled.
 *   ok       — every part is within its measured/configured envelope.
 *
 * Nothing here is character-specific: the character's own parts.json and the
 * character's section of hardware-safety.json are the only inputs.
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { getEffectiveWindow, readPartAngle } from './poseBounds.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.resolve(__dirname, '../../data');

export const HEALTH = Object.freeze({ OK: 'ok', DEGRADED: 'degraded', BLOCKED: 'blocked' });

const RANK = { ok: 0, degraded: 1, blocked: 2 };

const RETRACT_DIRECTIONS = new Set(['retract', 'reverse', 'down', 'in']);

// parts.json is read once per health pass for a whole library; cache briefly so
// annotating 34 poses does not mean 34 SD-card reads.
const PARTS_TTL_MS = 5000;
const _partsCache = new Map(); // characterId -> { at, parts }

export function invalidatePoseHealthCache() {
    _partsCache.clear();
}

async function loadParts(characterId) {
    const key = String(characterId);
    const cached = _partsCache.get(key);
    if (cached && (Date.now() - cached.at) < PARTS_TTL_MS) return cached.parts;

    let parts = [];
    try {
        const raw = await fs.readFile(path.join(DATA_DIR, `character-${characterId}`, 'parts.json'), 'utf8');
        const data = JSON.parse(raw);
        parts = Array.isArray(data) ? data : (data.parts || []);
    } catch (err) {
        if (!err || err.code !== 'ENOENT') {
            console.warn(`[poseHealth] Could not read parts for character ${characterId}: ${err.message}`);
        }
        parts = [];
    }
    _partsCache.set(key, { at: Date.now(), parts });
    return parts;
}

function worse(a, b) {
    return RANK[b] > RANK[a] ? b : a;
}

function normalizeType(type) {
    return String(type || '').replace(/-/g, '_');
}

/**
 * Evaluate one pose.
 *
 * @param {number|string} characterId
 * @param {Object} pose
 * @param {Array} [parts] - pre-loaded parts.json contents (avoids a re-read)
 * @returns {Promise<{status:string, reasons:Array, blockedParts:Array}>}
 */
export async function evaluatePoseHealth(characterId, pose, parts = null) {
    const allParts = parts || await loadParts(characterId);
    const reasons = [];
    const blockedParts = [];
    let status = HEALTH.OK;

    if (!pose || !Array.isArray(pose.parts) || pose.parts.length === 0) {
        return {
            status: HEALTH.BLOCKED,
            reasons: [{ partId: null, level: HEALTH.BLOCKED, code: 'no-parts', message: 'Pose has no parts to execute' }],
            blockedParts: []
        };
    }

    for (const posePart of pose.parts) {
        const partId = posePart.partId;
        // scenes.json uses string ids and poses.json uses numbers — compare as strings.
        const hwPart = allParts.find(p => String(p.id) === String(partId));

        if (!hwPart) {
            status = worse(status, HEALTH.BLOCKED);
            blockedParts.push(partId);
            reasons.push({
                partId, level: HEALTH.BLOCKED, code: 'missing-part',
                message: `Part ${partId} is not defined for this character`
            });
            continue;
        }

        if (hwPart.enabled === false) {
            status = worse(status, HEALTH.DEGRADED);
            reasons.push({
                partId, level: HEALTH.DEGRADED, code: 'part-disabled',
                message: `${hwPart.name || `Part ${partId}`} is disabled in parts.json`
            });
        }

        let window;
        try {
            window = await getEffectiveWindow(characterId, partId);
        } catch (err) {
            status = worse(status, HEALTH.DEGRADED);
            reasons.push({
                partId, level: HEALTH.DEGRADED, code: 'bounds-unavailable',
                message: `Could not resolve safe bounds for part ${partId}: ${err.message}`
            });
            continue;
        }

        if (window.blocked) {
            status = worse(status, HEALTH.BLOCKED);
            blockedParts.push(partId);
            reasons.push({
                partId, level: HEALTH.BLOCKED, code: 'quarantined',
                // blockReason is carried verbatim: it is the written explanation of
                // what a human has to do to clear the block, and paraphrasing it
                // loses the instruction.
                message: `${hwPart.name || `Part ${partId}`} is quarantined by hardware safety limits`,
                blockReason: window.blockReason
            });
            continue;
        }

        const target = posePart.target || {};
        const direction = target.direction != null ? String(target.direction).toLowerCase() : null;
        if (window.noRetractBelowMin && direction && RETRACT_DIRECTIONS.has(direction)) {
            status = worse(status, HEALTH.BLOCKED);
            blockedParts.push(partId);
            reasons.push({
                partId, level: HEALTH.BLOCKED, code: 'retract-blocked',
                message: `${hwPart.name || `Part ${partId}`} sits at its mechanical minimum; "${direction}" is refused by hardware safety limits`
            });
            continue;
        }

        const type = normalizeType(posePart.type || hwPart.type);
        const angle = readPartAngle(posePart);

        if (angle != null && (type === 'servo' || type === 'continuous_servo')) {
            if (window.lo != null && angle < window.lo) {
                status = worse(status, HEALTH.DEGRADED);
                reasons.push({
                    partId, level: HEALTH.DEGRADED, code: 'angle-clamped',
                    message: `${angle}° is below the safe floor ${window.lo}° and will be clamped`
                });
            } else if (window.hi != null && angle > window.hi) {
                status = worse(status, HEALTH.DEGRADED);
                reasons.push({
                    partId, level: HEALTH.DEGRADED, code: 'angle-clamped',
                    message: `${angle}° is above the safe ceiling ${window.hi}° and will be clamped`
                });
            }
            if (window.lo == null && window.hi == null) {
                status = worse(status, HEALTH.DEGRADED);
                reasons.push({
                    partId, level: HEALTH.DEGRADED, code: 'uncalibrated',
                    message: window.placeholderCalibration
                        ? `${hwPart.name || `Part ${partId}`} has only an autoGenerated placeholder calibration — its travel has never been measured`
                        : `${hwPart.name || `Part ${partId}`} has no calibrated or configured angle window`
                });
            }
        }

        const durationMs = target.durationMs ?? target.duration;
        if (window.maxDurationMs != null && durationMs != null && Number(durationMs) > window.maxDurationMs) {
            status = worse(status, HEALTH.DEGRADED);
            reasons.push({
                partId, level: HEALTH.DEGRADED, code: 'duration-capped',
                message: `duration ${durationMs}ms will be capped to ${window.maxDurationMs}ms`
            });
        }

        if (window.powerGroup) {
            status = worse(status, HEALTH.DEGRADED);
            reasons.push({
                partId, level: HEALTH.DEGRADED, code: 'shared-power-rail',
                message: `${hwPart.name || `Part ${partId}`} shares the "${window.powerGroup}" fused rail — its move is serialized, so this pose does not land all at once`
            });
        }
    }

    return { status, reasons, blockedParts };
}

/**
 * Annotate a whole library. Returns new pose objects with a `health` field;
 * the originals are not mutated and nothing is written back to disk.
 *
 * @param {number|string} characterId
 * @param {Array} poses
 * @returns {Promise<Array>}
 */
export async function annotatePoses(characterId, poses) {
    if (!Array.isArray(poses) || poses.length === 0) return [];
    const parts = await loadParts(characterId);
    const out = [];
    for (const pose of poses) {
        const health = await evaluatePoseHealth(characterId, pose, parts);
        out.push({ ...pose, health });
    }
    return out;
}

/** True when the pose can be performed at all (i.e. is not `blocked`). */
export function isPerformable(pose) {
    return !(pose && pose.health && pose.health.status === HEALTH.BLOCKED);
}

/**
 * Per-part safety summary for a character, for UIs that must refuse to add a
 * quarantined part. Keyed by String(partId) because that is the id spelling that
 * survives both file conventions.
 *
 * @param {number|string} characterId
 * @returns {Promise<Object>} map of partId -> descriptor
 */
export async function getPartSafetySummary(characterId) {
    const parts = await loadParts(characterId);
    const summary = {};
    for (const part of parts) {
        let window;
        try {
            window = await getEffectiveWindow(characterId, part.id);
        } catch (_) {
            continue;
        }
        summary[String(part.id)] = {
            partId: part.id,
            name: part.name || `Part ${part.id}`,
            type: part.type,
            enabled: part.enabled !== false,
            blocked: window.blocked,
            blockReason: window.blockReason,
            minAngle: window.lo,
            maxAngle: window.hi,
            calibrated: window.calibrated,
            placeholderCalibration: window.placeholderCalibration,
            maxDurationMs: window.maxDurationMs,
            powerGroup: window.powerGroup,
            noRetractBelowMin: window.noRetractBelowMin,
            notes: window.notes
        };
    }
    return summary;
}

export default {
    HEALTH,
    evaluatePoseHealth,
    annotatePoses,
    isPerformable,
    getPartSafetySummary,
    invalidatePoseHealthCache
};
