/**
 * Pose Bounds — the one place that decides what angle window a pose part may
 * occupy, and the only place allowed to add random variation to an authored angle.
 *
 * Why this exists
 * ---------------
 * Per-pose `jitterDeg` makes the same pose land slightly differently every time,
 * which is the difference between "cycling through positions" and "alive". The
 * entire risk of that feature is that a random offset walks a part past the limit
 * a human measured for it. So jitter is never added to a raw authored angle: the
 * angle is first clamped INTO the effective window, and the jitter amplitude is
 * then reduced to the headroom actually available on each side of it. A part
 * sitting on its own limit gets zero jitter toward that limit, not a clamp after
 * the fact.
 *
 * The effective window is the intersection of:
 *   - the part's calibration profile bounds, IGNORED when the profile is an
 *     `autoGenerated` placeholder (the store stamps a full 0-180 span on every
 *     uncalibrated absolute servo — that is a guess, not a measurement), and
 *   - the committed per-part window in `config/hardware-safety.json`.
 *
 * If a side of the window is unknown, jitter does not move that way at all.
 * An uncalibrated part with no configured limits therefore gets NO jitter — the
 * conservative reading, because there is no number to prove the offset is safe.
 * The downstream `applySafetyLimits` clamp in the hardware service is still in
 * force; it is the second net, not the first.
 */

import { getPartSafety } from '../hardwareService/safetyLimits.js';
import { getCalibrationStore, isPlaceholderProfile } from '../../server/calibration/store.js';

/** Nothing may request more than this much jitter, whatever a pose file says. */
export const MAX_JITTER_DEG = 15;

// Window lookups hit the calibration file and the safety config. The idle loop and
// micro-motion ask for them repeatedly, and this runs off an SD card, so cache
// briefly. Both underlying stores have their own caches; this one bounds the
// JSON.parse cost of the calibration file.
const WINDOW_TTL_MS = 5000;
const _windowCache = new Map(); // `${characterId}:${partId}` -> { at, value }

export function invalidatePoseBoundsCache() {
    _windowCache.clear();
}

function maxDefined(a, b) {
    if (a == null) return b;
    if (b == null) return a;
    return Math.max(a, b);
}

function minDefined(a, b) {
    if (a == null) return b;
    if (b == null) return a;
    return Math.min(a, b);
}

/**
 * Resolve the effective angle window and safety posture for one part.
 *
 * @param {number|string} characterId
 * @param {number|string} partId
 * @returns {Promise<{lo:number|null, hi:number|null, placeholderCalibration:boolean,
 *                    calibrated:boolean, blocked:boolean, blockReason:string|null,
 *                    powerGroup:string|null, maxSpeedPct:number|null,
 *                    maxDurationMs:number|null, noRetractBelowMin:boolean,
 *                    excludeFromAutomatedTests:boolean, notes:string|null}>}
 */
export async function getEffectiveWindow(characterId, partId) {
    const key = `${characterId}:${String(partId)}`;
    const cached = _windowCache.get(key);
    if (cached && (Date.now() - cached.at) < WINDOW_TTL_MS) return cached.value;

    let profile = null;
    try {
        // Always pass the character: part IDs are only unique within one.
        profile = await getCalibrationStore().get(partId, characterId);
    } catch (_) { /* uncalibrated — configured limits still apply */ }

    const safety = await getPartSafety(characterId, partId, profile);

    // A placeholder profile is not a measurement, so its bounds must not be read
    // as one. Centralised in the calibration store so every consumer agrees.
    const placeholder = isPlaceholderProfile(profile);
    const bounds = (!placeholder && profile && profile.bounds) || {};

    const value = {
        lo: maxDefined(bounds.minAngle ?? null, safety.minAngle ?? null),
        hi: minDefined(bounds.maxAngle ?? null, safety.maxAngle ?? null),
        placeholderCalibration: placeholder,
        calibrated: !!(profile && !placeholder),
        blocked: !!safety.blockAllMotion,
        blockReason: safety.blockReason || null,
        powerGroup: safety.powerGroup || null,
        maxSpeedPct: safety.maxSpeedPct ?? null,
        maxDurationMs: safety.maxDurationMs ?? null,
        noRetractBelowMin: !!safety.noRetractBelowMin,
        excludeFromAutomatedTests: !!safety.excludeFromAutomatedTests,
        notes: safety.notes || null
    };

    _windowCache.set(key, { at: Date.now(), value });
    return value;
}

/**
 * Clamp an angle into [lo, hi]. A null bound means "unknown", not "unbounded to 0".
 */
export function clampIntoWindow(angle, lo, hi) {
    let out = Number(angle);
    if (!Number.isFinite(out)) return angle;
    if (lo != null && out < lo) out = lo;
    if (hi != null && out > hi) out = hi;
    return out;
}

function roundDeg(value) {
    return Math.round(value * 10) / 10;
}

/**
 * Add bounded random variation to an angle.
 *
 * The offset is drawn from [-down, +up] where `down`/`up` are the jitter amplitude
 * capped by the headroom between the (already clamped) base angle and each side of
 * the window. An unknown side contributes zero headroom, so a part nobody has
 * measured never gets jittered toward the unknown.
 *
 * @param {number} baseAngle - authored angle
 * @param {number} jitterDeg - requested amplitude in degrees (± )
 * @param {number|null} lo - window floor, or null if unknown
 * @param {number|null} hi - window ceiling, or null if unknown
 * @param {function} [rng] - injectable [0,1) source for deterministic tests
 * @returns {number} angle guaranteed to sit inside [lo, hi]
 */
export function jitterWithinWindow(baseAngle, jitterDeg, lo, hi, rng = Math.random) {
    const base = clampIntoWindow(baseAngle, lo, hi);
    if (!Number.isFinite(Number(base))) return baseAngle;

    let amplitude = Number(jitterDeg);
    if (!Number.isFinite(amplitude) || amplitude <= 0) return base;
    amplitude = Math.min(amplitude, MAX_JITTER_DEG);

    // Unknown side => no travel that way. See the module header for why.
    const down = lo != null ? Math.min(amplitude, Math.max(0, base - lo)) : 0;
    const up = hi != null ? Math.min(amplitude, Math.max(0, hi - base)) : 0;
    if (down <= 0 && up <= 0) return base;

    const offset = -down + rng() * (down + up);
    // Round first, then clamp: rounding must never be the thing that leaves the window.
    return clampIntoWindow(roundDeg(base + offset), lo, hi);
}

/** A pose part carries an angle if any of the three spellings in use is set. */
export function readPartAngle(part) {
    if (!part) return null;
    const value = part.value ?? (part.target && part.target.angleDeg) ?? part.angleDeg;
    return value == null ? null : Number(value);
}

/** Write an angle back using whichever spelling the part already used. */
function writePartAngle(part, angle) {
    const out = { ...part };
    if (part.target && part.target.angleDeg != null) {
        out.target = { ...part.target, angleDeg: angle };
    } else if (part.value != null) {
        out.value = angle;
    } else if (part.angleDeg != null) {
        out.angleDeg = angle;
    } else if (part.target) {
        out.target = { ...part.target, angleDeg: angle };
    }
    return out;
}

/** Marker set on a runtime pose copy so jitter can never be applied twice. */
export const JITTER_APPLIED = '__jitterApplied';

/**
 * Return a copy of `pose` with every angular part jittered inside its own window.
 *
 * Non-angular parts (lights, actuators, motors) are passed through untouched —
 * "jitter" has no safe meaning for a timed actuator pulse.
 *
 * @param {Object} pose
 * @param {number|string} characterId
 * @param {Object} [options]
 * @param {number} [options.jitterDeg] - override the pose's own jitterDeg
 * @param {function} [options.rng]
 * @returns {Promise<{pose:Object, applied:Array, skipped:Array}>}
 */
export async function applyPoseJitter(pose, characterId, options = {}) {
    const applied = [];
    const skipped = [];
    if (!pose || !Array.isArray(pose.parts) || pose.parts.length === 0) {
        return { pose, applied, skipped };
    }
    if (pose[JITTER_APPLIED]) return { pose, applied, skipped };

    const rng = options.rng || Math.random;
    const poseJitter = options.jitterDeg != null ? options.jitterDeg : pose.jitterDeg;

    const parts = [];
    let changed = false;

    for (const part of pose.parts) {
        const base = readPartAngle(part);
        // Per-part jitterDeg wins over the pose-level value, so one twitchy part
        // does not force the whole pose to be twitchy (or vice versa).
        const requested = part.jitterDeg != null ? part.jitterDeg : poseJitter;
        if (base == null || requested == null || Number(requested) <= 0) {
            parts.push(part);
            continue;
        }

        let window;
        try {
            window = await getEffectiveWindow(characterId, part.partId);
        } catch (err) {
            // Never let a bounds lookup failure turn into an unbounded offset.
            skipped.push({ partId: part.partId, reason: `bounds lookup failed: ${err.message}` });
            parts.push(part);
            continue;
        }

        const jittered = jitterWithinWindow(base, requested, window.lo, window.hi, rng);
        if (jittered === base) {
            skipped.push({
                partId: part.partId,
                reason: window.lo == null && window.hi == null
                    ? 'no measured window — jitter needs a bound to stay inside of'
                    : 'no headroom inside the window at this angle'
            });
            parts.push(part);
            continue;
        }

        applied.push({ partId: part.partId, from: base, to: jittered, lo: window.lo, hi: window.hi });
        parts.push(writePartAngle(part, jittered));
        changed = true;
    }

    if (!changed) return { pose, applied, skipped };

    const out = { ...pose, parts };
    Object.defineProperty(out, JITTER_APPLIED, { value: true, enumerable: false });
    return { pose: out, applied, skipped };
}

export default {
    MAX_JITTER_DEG,
    getEffectiveWindow,
    clampIntoWindow,
    jitterWithinWindow,
    applyPoseJitter,
    readPartAngle,
    invalidatePoseBoundsCache,
    JITTER_APPLIED
};
