import fs from 'fs/promises';
import path from 'path';
import { writeJsonAtomic, withFileLock } from '../../services/atomicStore.js';
import { readConfig } from '../../services/configService.js';

// MB_CALIBRATION_FILE redirects the whole store at a different file.
//
// It exists because this file is the node's ONLY record of measured travel and it
// is deliberately untracked (v8.1.4 untracked it to stop per-node ID collisions),
// so git cannot restore it and nothing else can either. A dozen unit tests inject
// synthetic parts and drive the real calibration endpoints, snapshotting this file
// in before() and writing it back in after(). Any run that does not reach after()
// — Ctrl-C, a timeout, an OOM, a killed mocha — leaves whatever the test wrote as
// the node's permanent calibration. That is not hypothetical: on 2026-09-12 Mina
// was left with six autoGenerated placeholders. His jaw lost its measured 28-84°
// window and his neck lost `capability.invert` plus its 48-180° window, so every
// commanded angle drove to the mirror image, into the stop. Three other characters'
// profiles were dropped from the file entirely.
//
// tests/setup.js points this at a throwaway copy, so a unit run physically cannot
// reach the node's calibration however it dies.
const DEFAULT_CAL_PATH = process.env.MB_CALIBRATION_FILE
  ? path.resolve(process.env.MB_CALIBRATION_FILE)
  : path.resolve(process.cwd(), 'data/calibration_profiles.json');

/**
 * Where the calibration store actually reads and writes.
 *
 * Tests that snapshot the file by raw path must use this, not their own
 * path.join(APP_ROOT, 'data', ...) — otherwise they restore the live file while
 * the code under test writes the sandbox, which is how the live file got edited
 * by a suite that believed it was putting everything back.
 */
export function calibrationFilePath() {
  return DEFAULT_CAL_PATH;
}

// Part IDs are NOT globally unique — character-1 and character-3 both define a
// part id 5 referring to different physical hardware. Keying calibration profiles
// by bare partId let one character's calibration overwrite another's (and drive a
// servo to the wrong, possibly damaging, bounds). Profiles are therefore keyed by
// `${characterId}:${partId}`.
//
// Safety / backward-compatibility: reads fall back to a legacy bare-`partId` entry
// when no character-scoped entry exists, so existing calibration data keeps working
// until a part is re-calibrated (which writes the scoped key). This makes the change
// strictly non-regressive: at worst a reader gets today's shared value.
//
// The character defaults to the node's selected character (a MonsterBox node runs
// one character), resolved from config and cached briefly to avoid an SD read on
// every lookup during scene execution. Callers that know the character (scene
// executor, jaw/head services) pass it explicitly.

let _selCache = { id: undefined, at: 0 };
const SEL_TTL_MS = 2000;

async function selectedCharacterId() {
  const now = Date.now();
  if (_selCache.id !== undefined && (now - _selCache.at) < SEL_TTL_MS) {
    return _selCache.id;
  }
  try {
    const cfg = await readConfig();
    _selCache = { id: (cfg && cfg.selectedCharacter != null) ? cfg.selectedCharacter : null, at: now };
  } catch (_) {
    _selCache = { id: null, at: now };
  }
  return _selCache.id;
}

// Test/hot-swap hook: forget the cached selected character.
export function invalidateSelectedCharacterCache() {
  _selCache = { id: undefined, at: 0 };
}

function scopedKey(characterId, partId) {
  return `${characterId}:${String(partId)}`;
}

/**
 * Is this profile a placeholder rather than a real calibration?
 *
 * The store stamps every uncalibrated absolute-servo with the full 0-180 mechanical
 * span and marks it `autoGenerated`; the flag is only cleared once a human actually
 * calibrates the part. Consumers that read `bounds` without checking this treat a
 * guess as a measurement — which drove a servo with hand-set 63/131 markers across
 * its entire span. Named here so every consumer checks the same thing.
 *
 * Callers should prefer real `parts.json` markers over a placeholder, and fall back
 * to the placeholder only when nothing better exists.
 */
export function isPlaceholderProfile(profile) {
  return !!(profile && profile.autoGenerated);
}

// Narrowest angle window we will accept as a measurement. Anything tighter is a
// failed calibration run, not a tight part: no servo is usefully calibrated to
// less than a degree of travel.
const MIN_MEASURED_SPAN_DEG = 1;

/**
 * Is this an angle window that would pin a servo in place rather than bound it?
 *
 * set-min and set-max each record wherever the servo currently *is*. If the servo
 * does not visibly move — a dead channel, or a command path that ignored the
 * requested angle — an operator naturally presses both at the same position, and
 * the profile stores minAngle === maxAngle. Every later command then clamps to
 * that single value, so the part can never move again, and the symptom ("the
 * servo is dead") is indistinguishable from the cause the operator was chasing.
 *
 * Mina's neck reached exactly this state: {minAngle:108, maxAngle:108}. The
 * existing guard in set-min/set-max only swaps an INVERTED window; equality
 * passed straight through.
 */
export function isDegenerateWindow(bounds) {
  if (!bounds) return false;
  const { minAngle, maxAngle, minP, maxP } = bounds;
  if (typeof minAngle === 'number' && typeof maxAngle === 'number') {
    // NaN comparisons are false, so test finiteness explicitly — a NaN bound
    // is a failed capture, not a window.
    if (!Number.isFinite(minAngle) || !Number.isFinite(maxAngle)) return true;
    if ((maxAngle - minAngle) < MIN_MEASURED_SPAN_DEG) return true;
  }
  // Open-loop parts have the same failure shape in normalized units: set-min
  // and set-max both declare "here is the endpoint", so a part that never
  // moved gets minP === maxP and every later command collapses to a 0ms pulse.
  if (typeof minP === 'number' && typeof maxP === 'number') {
    if (!Number.isFinite(minP) || !Number.isFinite(maxP)) return true;
    if ((maxP - minP) <= 0) return true;
  }
  return false;
}

/**
 * The calibrated window for a profile, or null when there isn't one.
 *
 * Use this instead of reaching for `profile.bounds` — it is the single place that
 * knows a placeholder's span is a guess and a pinned window is not a measurement.
 */
export function calibratedBounds(profile) {
  if (!profile || isPlaceholderProfile(profile)) return null;
  if (isDegenerateWindow(profile.bounds)) return null;
  return profile.bounds || null;
}

/**
 * Is this part stamped as calibrated?
 *
 * "Calibrated" used to be implicit — the inverse of `autoGenerated`, flipped only as
 * a side effect of set-min/set-max. An operator had no way to say "yes, I measured
 * this myself" or "no, this drifted, stop trusting it", so a stale calibration stayed
 * labelled good forever and a hand-verified part could never be blessed.
 *
 * The explicit stamp lives in `profile.calibrated`. It is a LABEL, never a licence:
 * a degenerate window can never read as calibrated however the flag is set, because
 * handing a pinned window to something that moves hardware freezes the part.
 */
export function isCalibrated(profile) {
  if (!profile) return false;
  if (isDegenerateWindow(profile.bounds)) return false;
  if (typeof profile.calibrated === 'boolean') return profile.calibrated;
  return !isPlaceholderProfile(profile);
}

/**
 * Shape a stored profile for READING.
 *
 * Every consumer of a placeholder profile was fixed individually in v9.0.0, but
 * that only fixed the consumers that existed. The design still invited the bug
 * back: the obvious line of code — `profile.bounds.minAngle` — silently promoted a
 * 0-180 guess to a measurement, and nothing about the value said otherwise. A new
 * reader writing the natural thing reintroduced a servo driven past its stops.
 *
 * So the read path answers the natural question honestly: on a placeholder,
 * `bounds` is null, because there are no measured bounds. The guess is still
 * available under `placeholderBounds`, a name that cannot be mistaken for a
 * measurement, for the two callers that deliberately want a last-resort span.
 *
 * A degenerate window is withheld the same way and for the same reason: it is not
 * a measurement, and handing it to a caller that moves hardware freezes the part.
 * It is surfaced as `degenerateBounds` so the calibration page can tell the
 * operator their run needs redoing rather than silently showing nothing.
 *
 * Writers must use `getRaw()` — a read-modify-write of this view would drop the
 * placeholder span on save.
 */
function shapeForRead(profile) {
  if (!profile) return profile;

  if (isDegenerateWindow(profile.bounds)) {
    const view = Object.assign({}, profile);
    view.bounds = null;
    view.degenerateBounds = profile.bounds;
    return view;
  }

  if (!isPlaceholderProfile(profile)) return profile;
  const view = Object.assign({}, profile);
  view.bounds = null;
  view.placeholderBounds = profile.bounds || null;
  return view;
}

export class JsonCalibrationStore {
  constructor(filePath) {
    this.filePath = filePath || DEFAULT_CAL_PATH;
    // mtime+size-validated parse cache. load() sits on two hot paths — every
    // hardware command's bounds check and the pose-health N+1 on
    // GET /poses/api/poses — and without this each call re-read and re-parsed
    // the whole file from the SD card.
    this._fileCache = null;
  }

  /**
   * The raw file, keyed as stored. This is a dump for tooling and for
   * snapshot/restore — it is NOT the safe read path; use get()/getRaw().
   */
  async load() {
    try {
      const stat = await fs.stat(this.filePath);
      if (this._fileCache
          && this._fileCache.mtimeMs === stat.mtimeMs
          && this._fileCache.size === stat.size) {
        return this._fileCache.data;
      }
      const raw = await fs.readFile(this.filePath, 'utf8');
      const data = JSON.parse(raw || '{}');
      this._fileCache = { mtimeMs: stat.mtimeMs, size: stat.size, data };
      return data;
    } catch (e) {
      if (e && e.code === 'ENOENT') return {};
      throw e;
    }
  }

  /**
   * Snapshot the file before a write that would LOSE a measurement.
   *
   * This file has been wiped twice (2026-09-06 and 2026-09-12) and neither time
   * was there anything to restore from: it is untracked on purpose, so git
   * cannot help, and the only reason the second wipe was recoverable at all is
   * that someone had happened to leave a manual copy in a home directory. A
   * measured window is minutes of an operator's time with eyes on the hardware
   * and hands on the part; losing one should not be a one-way door.
   *
   * Deliberately NOT a backup on every write. An ordinary calibration run
   * upserts constantly and this box writes to an SD card, so the snapshot fires
   * only when a write would drop a profile that is currently marked measured, or
   * demote one back to a placeholder — which is what a clear-all, a bad restore
   * or a half-finished migration looks like, and is not what routine use looks
   * like. Ten snapshots are kept.
   */
  async _snapshotIfLosingMeasurements(next) {
    // Read the file from disk, NOT through load(). load() hands back its cached
    // object, and delete()/upsert() mutate that very object before calling save(),
    // so comparing against it compared the new data with itself: nothing was ever
    // "lost" and no snapshot was ever written — including for the single-part
    // Clear that erased Mina's measured jaw window at 12:17 on 2026-09-12.
    let current;
    try {
      current = JSON.parse((await fs.readFile(this.filePath, 'utf8')) || '{}');
    } catch (_) {
      return; // nothing readable to lose
    }
    if (!current || typeof current !== 'object') return;

    const measured = (p) => !!(p && p.autoGenerated === false);
    const lost = Object.keys(current).filter((key) => {
      if (!measured(current[key])) return false;
      return !measured(next && next[key]);
    });
    if (lost.length === 0) return;

    const dir = path.join(path.dirname(this.filePath), 'calibration-backups');
    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    try {
      await fs.mkdir(dir, { recursive: true });
      await writeJsonAtomic(path.join(dir, `calibration_profiles-${stamp}.json`), current);
      console.warn(
        `🗄️  Calibration snapshot written before a write that drops measured profile(s) ` +
        `${lost.join(', ')} — restore from ${dir} if this was not intended`);

      const keep = 10;
      const files = (await fs.readdir(dir))
        .filter((f) => f.startsWith('calibration_profiles-') && f.endsWith('.json'))
        .sort();
      for (const stale of files.slice(0, Math.max(0, files.length - keep))) {
        await fs.unlink(path.join(dir, stale)).catch(() => {});
      }
    } catch (err) {
      // A failed snapshot must never block the write the caller asked for.
      console.warn(`🗄️  Could not snapshot calibration before overwrite: ${err.message}`);
    }
  }

  async save(data) {
    await fs.mkdir(path.dirname(this.filePath), { recursive: true });
    await this._snapshotIfLosingMeasurements(data);
    // Atomic write so an interrupted calibration write can't corrupt the file.
    await writeJsonAtomic(this.filePath, data);
    // The atomic rename lands with a fresh mtime, but drop the cache anyway so
    // a same-millisecond rewrite can never serve the pre-save snapshot.
    this._fileCache = null;
  }

  async _resolveCharacter(characterId) {
    return characterId !== undefined ? characterId : await selectedCharacterId();
  }

  /**
   * Read a profile for USE. Placeholder bounds are withheld — see shapeForRead().
   */
  async get(partId, characterId) {
    return shapeForRead(await this.getRaw(partId, characterId));
  }

  /**
   * Read the stored record verbatim, placeholder span included.
   *
   * For writers (read-modify-write) and for callers whose job is to report on the
   * calibration itself — the calibration page needs to show an operator the span
   * they are about to replace. Anything that MOVES hardware should use get().
   */
  async getRaw(partId, characterId) {
    const cid = await this._resolveCharacter(characterId);
    const all = await this.load();
    if (cid != null) {
      const scoped = all[scopedKey(cid, partId)];
      if (scoped) return scoped;
    }
    // Legacy fallback: a pre-namespacing bare-partId entry.
    return all[String(partId)] || null;
  }

  async upsert(profile, characterId) {
    // Serialize the load→mutate→save so two concurrent calibration writes don't
    // each read the same snapshot and clobber the other (last-writer-wins).
    return withFileLock(`calibration:${this.filePath}`, async () => {
      const cid = characterId !== undefined
        ? characterId
        : (profile && profile.characterId != null ? profile.characterId : await selectedCharacterId());
      const all = await this.load();
      const key = cid != null ? scopedKey(cid, profile.partId) : String(profile.partId);
      // updatedAt means "last written". lastCalibratedAt is NOT stamped here —
      // upsert runs for preset adds, channel reconciles and auto-creates, so
      // stamping it made "last calibrated" mean "last touched" and a
      // never-measured part could show a today timestamp (v11 audit F13). The
      // genuine measurement writers (set-min/set-max, bounds saves, the
      // Calibrated stamp) set it explicitly; everything else carries the
      // existing value through unchanged.
      all[key] = Object.assign({}, profile, {
        characterId: cid != null ? cid : (profile.characterId != null ? profile.characterId : undefined),
        updatedAt: new Date().toISOString()
      });
      await this.save(all);
    });
  }

  async list() {
    const all = await this.load();
    return Object.values(all).map(shapeForRead);
  }

  async delete(partId, characterId) {
    return withFileLock(`calibration:${this.filePath}`, async () => {
      const cid = await this._resolveCharacter(characterId);
      const all = await this.load();
      const scoped = cid != null ? scopedKey(cid, partId) : null;
      // Prefer deleting the character-scoped entry; fall back to the legacy bare key.
      const key = (scoped && all[scoped]) ? scoped : String(partId);
      if (!all[key]) return false;
      delete all[key];
      await this.save(all);
      return true;
    });
  }

  /**
   * Delete several profiles in ONE write, so a clear-all produces exactly one
   * snapshot of the untouched file. Deleting part by part wrote one snapshot per
   * part, and with ten kept, clearing more than ten measured parts rotated the
   * only complete pre-clear copy away before the clear had even finished.
   */
  async deleteMany(partIds, characterId) {
    return withFileLock(`calibration:${this.filePath}`, async () => {
      const cid = await this._resolveCharacter(characterId);
      const all = Object.assign({}, await this.load());
      const removed = [];
      for (const partId of partIds) {
        const scoped = cid != null ? scopedKey(cid, partId) : null;
        const key = (scoped && all[scoped]) ? scoped : String(partId);
        if (!all[key]) continue;
        delete all[key];
        removed.push(partId);
      }
      if (removed.length > 0) await this.save(all);
      return removed;
    });
  }
}

let instance = null;
export function getCalibrationStore(filePath) {
  if (!instance) instance = new JsonCalibrationStore(filePath);
  return instance;
}

export default { JsonCalibrationStore, getCalibrationStore, calibrationFilePath, invalidateSelectedCharacterCache, isPlaceholderProfile, calibratedBounds, isCalibrated, isDegenerateWindow };
