#!/usr/bin/env bash
# One-command close-out for Sir Dragomir's bench session (2026-08-22).
# Run ON the node:  bash scripts/bench/knight-finish.sh
#
# Idempotent. Asserts the operator's FINAL channel map, ruled at the bench
# 2026-08-22 ("for once and always"):
#
#     JAW  = channel 3     HEAD = channel 7 (multi-turn, 0-900 real degrees)
#     BOX  = channel 11
#
# Canonical record: docs/hardware/PCA9685-CHANNEL-MAP-DRAGOMIR.md. Earlier
# versions of this script asserted two other maps (head=11, then jaw=7) and
# each wrong assertion re-created a channel collision at the bench — do NOT
# edit these numbers without the operator's explicit direction.
set -u

H="https://localhost:3000"
B="$H/setup/calibration/api/parts"
say(){ printf '\n== %s ==\n' "$*"; }

say "waiting for the MonsterBox server"
up=0
for i in $(seq 1 30); do
  if curl -sk -o /dev/null "$H/health"; then up=1; break; fi
  sleep 2
done
if [ "$up" != "1" ]; then
  echo "server never answered on $H — sudo systemctl restart monsterbox.service and re-run" >&2
  exit 1
fi

say "asserting the FINAL channel map (jaw=3, head=7 multi-turn 0-900, box=11)"
curl -sk -X POST "$B/1/overrides" -H 'Content-Type: application/json' \
  -d '{"overrides":{"channel":7,"servoType":"multi-turn","rotationRangeDeg":900}}'; echo
curl -sk -X POST "$B/2/overrides" -H 'Content-Type: application/json' \
  -d '{"overrides":{"channel":3,"servoType":"standard"}}'; echo
curl -sk -X POST "$B/3/overrides" -H 'Content-Type: application/json' \
  -d '{"overrides":{"channel":11,"servoType":"standard"}}'; echo

say "what actually landed (head ch7 multi-turn/900; jaw ch3; box ch11)"
curl -sk "$B/1" | python3 -c "import json,sys; print('head:', json.load(sys.stdin)['part']['config'])"
curl -sk "$B/2" | python3 -c "import json,sys; print('jaw :', json.load(sys.stdin)['part']['config'])"
curl -sk "$B/3" | python3 -c "import json,sys; print('box :', json.load(sys.stdin)['part']['config'])"

# Any two motion parts sharing a channel is the collision class that burned
# this bench three times tonight — refuse to end quietly if it recurs.
DUPES=$(for p in 1 2 3; do
  curl -sk "$B/$p" | python3 -c "import json,sys; print(json.load(sys.stdin)['part']['config'].get('channel'))"
done | sort | uniq -d)
if [ -n "$DUPES" ]; then
  echo
  echo "!! CHANNEL COLLISION: more than one part claims channel(s): $DUPES"
  echo "!! Fix with one overrides curl per part before driving anything."
fi

say "head calibration profile (self-heals to absolute-servo, maxAngleDeg 900, on this read)"
curl -sk "$H/api/calibration/1/profile" | \
  python3 -c "import json,sys; p=json.load(sys.stdin)['profile']; print('kind:', p['capability'].get('kind'), '| maxAngleDeg:', p['capability'].get('maxAngleDeg'), '| autoGenerated:', p.get('autoGenerated'))"

say "DONE — remaining steps are hands-on, in this order"
cat <<'EOS'
1. RELEASE before touching leads (ever): the Release button on the part, or
     curl -sk -X POST https://localhost:3000/api/calibration/<partId>/release
2. First head move — eyes on it, hand on power, cable slack:
     curl -sk -X POST https://localhost:3000/api/calibration/1/goto \
       -H 'Content-Type: application/json' -d '{"angle":450,"calibrationOverride":true}'
3. /setup/calibration -> Head Servo (reads 0-900): nudge outward
   (fine/med/coarse = 10/25/75 REAL degrees, daemon-fast), Set Min at the safe
   CCW end, Set Max at the safe CW end, cable margin on both, flip Calibrated.
4. Box (ch11): Set Min (closed) / Set Max (open), then flip its Calibrated
   stamp. Jaw (ch3): verify its window, re-measure if cleared.
5. If any part refuses with an error, the reason is REAL now (no more silent
   success) — read it, check /var/log/monsterbox.err, and fix the named cause
   rather than retrying.
EOS
