#!/usr/bin/env bash
# One-command close-out for Sir Dragomir's bench session (2026-08-22).
# Run ON the node:  bash scripts/bench/knight-finish.sh
#
# Idempotent. Asserts the operator's CONFIRMED channel map exactly once —
# jaw = ch7, head = ch11 (multi-turn, 0-900 real degrees) — verifies what
# actually landed, heals the head's calibration profile (the server rebuilds a
# placeholder profile to match the part's declared type on first touch), and
# prints the remaining hands-on steps. It never guesses the box's channel:
# that is printed for a human to judge against the physical pin.
set -u

H="https://localhost:3000"
B="$H/setup/calibration/api/parts"
say(){ printf '\n== %s ==\n' "$*"; }

say "waiting for the MonsterBox server"
up=0
for i in $(seq 1 30); do
  if curl -sk -o /dev/null "$H/health"; then up=1; break; fi
  sleep 2
done
if [ "$up" != "1" ]; then
  echo "server never answered on $H — sudo systemctl restart monsterbox.service and re-run" >&2
  exit 1
fi

say "asserting the operator's channel map (jaw=7, head=11 multi-turn 0-900)"
curl -sk -X POST "$B/1/overrides" -H 'Content-Type: application/json' \
  -d '{"overrides":{"channel":11,"servoType":"multi-turn","rotationRangeDeg":900}}'; echo
curl -sk -X POST "$B/2/overrides" -H 'Content-Type: application/json' \
  -d '{"overrides":{"channel":7,"servoType":"standard"}}'; echo

say "what actually landed (head must say channel 11 / multi-turn / 900; jaw channel 7)"
curl -sk "$B/1" | python3 -c "import json,sys; print('head:', json.load(sys.stdin)['part']['config'])"
curl -sk "$B/2" | python3 -c "import json,sys; print('jaw :', json.load(sys.stdin)['part']['config'])"
curl -sk "$B/3" | python3 -c "import json,sys; print('box :', json.load(sys.stdin)['part']['config'])"

say "head calibration profile (self-heals to absolute-servo, maxAngleDeg 900, on this read)"
curl -sk "$H/api/calibration/1/profile" | \
  python3 -c "import json,sys; p=json.load(sys.stdin)['profile']; print('kind:', p['capability'].get('kind'), '| maxAngleDeg:', p['capability'].get('maxAngleDeg'), '| autoGenerated:', p.get('autoGenerated'))"

say "DONE — remaining steps are hands-on, in this order"
cat <<'EOS'
1. RELEASE before touching leads (ever): the Release button on the part, or
     curl -sk -X POST https://localhost:3000/api/calibration/<partId>/release
2. First head move — eyes on it, hand on power, cable slack:
     curl -sk -X POST https://localhost:3000/api/calibration/1/goto \
       -H 'Content-Type: application/json' -d '{"angle":450,"calibrationOverride":true}'
3. /setup/calibration -> Head Servo (reads 0-900): nudge outward
   (fine/med/coarse = 10/25/75 REAL degrees, daemon-fast), Set Min at the safe
   CCW end, Set Max at the safe CW end, cable margin on both, flip Calibrated.
4. Box check: the box config channel printed above. If commanding the BOX
   moves the HEAD, they share channel 11 — set the box's real channel with one
   overrides curl on part 3, then Set Min (closed) / Set Max (open) on the box.
5. Report "head calibrated" so the physical-faults entry for part 1 gets
   removed from the repo and deployed.
EOS
