site_name: MonsterBox Documentation
theme:
  name: material
nav:
  - Home: index.md
  - Installation: install.md
  - Usage Guide: usage.md
  - Configuration: config.md
  - Directory Structure: structure.md
  - FAQ / Troubleshooting: faq.md
  - License: license.md
