/**
 * Losing a measured calibration window must leave a restorable snapshot.
 *
 * The first version of this guard compared the new data against load()'s cached
 * object — the same object delete()/upsert() had just mutated — so it never saw
 * a loss and never wrote a snapshot. Mina's measured 28-84° jaw window was
 * cleared on 2026-09-12 with nothing left to restore from. These tests warm the
 * cache first, which is exactly the condition that hid the bug.
 */

import { expect } from 'chai';
import fs from 'fs/promises';
import os from 'os';
import path from 'path';
import { JsonCalibrationStore } from '../../server/calibration/store.js';

const measured = (partId, minAngle, maxAngle) => ({
  partId,
  capability: { kind: 'absolute-servo' },
  bounds: { minAngle, maxAngle },
  autoGenerated: false
});

describe('Calibration store — snapshot before losing a measurement', function () {
  let dir;
  let file;
  let store;

  beforeEach(async function () {
    dir = await fs.mkdtemp(path.join(os.tmpdir(), 'mb-cal-loss-'));
    file = path.join(dir, 'calibration_profiles.json');
    store = new JsonCalibrationStore(file);
  });

  afterEach(async function () {
    await fs.rm(dir, { recursive: true, force: true });
  });

  async function snapshots() {
    try {
      const names = await fs.readdir(path.join(dir, 'calibration-backups'));
      return Promise.all(names.sort().map(async (n) =>
        JSON.parse(await fs.readFile(path.join(dir, 'calibration-backups', n), 'utf8'))));
    } catch (err) {
      if (err.code === 'ENOENT') return [];
      throw err;
    }
  }

  it('writes no snapshot for ordinary measured writes', async function () {
    await store.upsert(measured(1, 28, 84), 2);
    await store.upsert(measured(1, 30, 80), 2);
    expect(await snapshots()).to.have.length(0);
  });

  it('snapshots the measured window before a single-part delete (warm cache)', async function () {
    await store.upsert(measured(1, 28, 84), 2);
    await store.load(); // warm the cache — the condition that hid the original bug
    await store.delete(1, 2);

    const snaps = await snapshots();
    expect(snaps, 'one snapshot').to.have.length(1);
    expect(snaps[0]['2:1'].bounds).to.deep.equal({ minAngle: 28, maxAngle: 84 });
    expect(await store.getRaw(1, 2)).to.equal(null);
  });

  it('snapshots before an upsert demotes a measured profile to a placeholder', async function () {
    await store.upsert(measured(1, 28, 84), 2);
    await store.load();
    await store.upsert({ partId: 1, bounds: { minAngle: 0, maxAngle: 180 }, autoGenerated: true }, 2);

    const snaps = await snapshots();
    expect(snaps).to.have.length(1);
    expect(snaps[0]['2:1'].autoGenerated).to.equal(false);
  });

  it('clears many parts in one write, leaving ONE complete pre-clear snapshot', async function () {
    const ids = Array.from({ length: 12 }, (_, i) => i + 1);
    for (const id of ids) await store.upsert(measured(id, 10 + id, 100 + id), 2);
    await store.upsert(measured(1, 5, 50), 3); // another character's part 1 must survive

    const removed = await store.deleteMany(ids, 2);
    expect(removed).to.deep.equal(ids);

    const snaps = await snapshots();
    expect(snaps, 'exactly one snapshot, not one per part').to.have.length(1);
    for (const id of ids) expect(snaps[0][`2:${id}`], `snapshot holds 2:${id}`).to.not.equal(undefined);

    const after = await store.load();
    expect(Object.keys(after)).to.deep.equal(['3:1']);
  });
});
