/**
 * v11 audit F11 — calibrated-stamp-only-on-hidden-page.
 *
 * POST /api/calibration/:partId/calibrated is the only way to RETIRE a
 * measured window (calibrated:false forces autoGenerated:true, which makes
 * calibratedBounds() withhold the window from every runtime consumer) and the
 * only explicit bless. Until now its sole caller was the legacy unified page,
 * reachable only through old redirect URLs — the nav-linked page operators
 * actually use could display "(unmeasured)" but never change it.
 *
 * Pinned here: (1) the MAIN calibration page ships the stamp control, and
 * (2) the endpoint's bless/retire round-trip works, including the honest
 * warning when blessing a never-measured default span.
 */

import { expect } from 'chai';
import request from 'supertest';
import express from 'express';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const APP_ROOT = path.resolve(__dirname, '..', '..');
const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';

const SYNTH_PART_ID = 987655;

describe('Calibrated stamp on the main page (F11)', function () {
  this.timeout(20000);

  it('the nav-linked /setup/calibration page carries the stamp control', async function () {
    const res = await request(BASE_URL).get('/setup/calibration').expect(200);
    expect(res.text, 'stamp checkbox must exist on the main page').to.include('calibratedToggle');
    expect(res.text, 'stamp handler must be wired on the main page').to.include('toggleCalibratedStamp');
  });

  describe('stamp endpoint round-trip (in-process router)', function () {
    let app;
    let partsPath;
    const savedFiles = new Map();

    before(async function () {
      const { readConfig } = await import('../../services/configService.js');
      const cfg = await readConfig();
      const characterId = cfg && cfg.selectedCharacter;
      if (characterId == null) this.skip();

      partsPath = path.join(APP_ROOT, 'data', `character-${characterId}`, 'parts.json');
      for (const f of [partsPath, path.join(APP_ROOT, 'data', 'calibration_profiles.json')]) {
        try { savedFiles.set(f, await fs.readFile(f, 'utf8')); } catch (_) { savedFiles.set(f, null); }
      }

      const parts = JSON.parse(savedFiles.get(partsPath) || '[]');
      parts.push({
        id: String(SYNTH_PART_ID),
        name: 'F11 Stamp Test Servo (synthetic)',
        type: 'servo',
        enabled: true,
        config: { servoType: 'standard', controllerType: 'pca9685', channel: 15, address: 64 }
      });
      await fs.writeFile(partsPath, JSON.stringify(parts, null, 2), 'utf8');

      const { default: router } = await import('../../server/calibration/router.js');
      app = express();
      app.use('/api/calibration', router);

      // Auto-create the profile (untouched 0-180 default span, autoGenerated).
      await request(app).get(`/api/calibration/${SYNTH_PART_ID}/profile`).expect(200);
    });

    after(async function () {
      for (const [f, content] of savedFiles) {
        try {
          if (content !== null) await fs.writeFile(f, content, 'utf8');
          else await fs.rm(f, { force: true });
        } catch (_) { /* best effort */ }
      }
    });

    it('blesses a part, but warns when the span was never actually measured', async function () {
      const res = await request(app)
        .post(`/api/calibration/${SYNTH_PART_ID}/calibrated`)
        .send({ calibrated: true })
        .expect(200);
      expect(res.body.success).to.equal(true);
      expect(res.body.calibrated).to.equal(true);
      expect(res.body.warning, 'blessing an untouched 0-180 default must not be silent')
        .to.match(/never been measured/i);
    });

    it('retires trust: calibrated:false makes the profile a placeholder again', async function () {
      const res = await request(app)
        .post(`/api/calibration/${SYNTH_PART_ID}/calibrated`)
        .send({ calibrated: false })
        .expect(200);
      expect(res.body.success).to.equal(true);
      expect(res.body.calibrated).to.equal(false);

      const prof = await request(app)
        .get(`/api/calibration/${SYNTH_PART_ID}/profile`)
        .expect(200);
      const p = prof.body.profile || prof.body;
      expect(p.autoGenerated, 'a retired window must read as unmeasured everywhere').to.equal(true);
    });
  });
});
