/**
 * Unit tests for the degenerate calibration-window guard.
 *
 * Discovered on Mina's neck (part 2): set-min and set-max each record the
 * servo's CURRENT angle, so pressing both while the servo was not visibly
 * moving stored {minAngle:108, maxAngle:108}. applySafetyLimits then clamped
 * every command to exactly 108°, freezing the part forever — a software state
 * indistinguishable from the dead servo the operator was diagnosing.
 *
 * The guard has two layers, tested here:
 *   - store.js withholds a degenerate window from readers (like placeholders),
 *     surfacing it as `degenerateBounds` instead of `bounds`;
 *   - calibratedBounds() never reports a degenerate window as a measurement.
 */

import { expect } from 'chai';
import {
  isDegenerateWindow,
  calibratedBounds,
  isPlaceholderProfile
} from '../../server/calibration/store.js';

describe('Degenerate calibration windows', function () {
  describe('isDegenerateWindow', function () {
    it('flags an equal min/max window (the frozen-neck case)', function () {
      expect(isDegenerateWindow({ minAngle: 108, maxAngle: 108 })).to.equal(true);
    });

    it('flags a sub-degree window as not a measurement', function () {
      expect(isDegenerateWindow({ minAngle: 100, maxAngle: 100.5 })).to.equal(true);
    });

    it('accepts a genuinely narrow but real window', function () {
      expect(isDegenerateWindow({ minAngle: 85, maxAngle: 95 })).to.equal(false);
    });

    it('accepts a full-span window', function () {
      expect(isDegenerateWindow({ minAngle: 0, maxAngle: 180 })).to.equal(false);
    });

    it('ignores bounds shapes that carry no angle window', function () {
      expect(isDegenerateWindow(null)).to.equal(false);
      expect(isDegenerateWindow({})).to.equal(false);
      expect(isDegenerateWindow({ minP: 0, maxP: 1 })).to.equal(false);
      expect(isDegenerateWindow({ minAngle: 90 })).to.equal(false);
    });
  });

  describe('calibratedBounds', function () {
    it('withholds a degenerate window from movers', function () {
      const profile = {
        autoGenerated: false,
        bounds: { minAngle: 108, maxAngle: 108 }
      };
      expect(calibratedBounds(profile)).to.equal(null);
    });

    it('still returns a real measured window', function () {
      const profile = {
        autoGenerated: false,
        bounds: { minAngle: 22, maxAngle: 91 }
      };
      expect(calibratedBounds(profile)).to.deep.equal({ minAngle: 22, maxAngle: 91 });
    });

    it('still withholds placeholder spans (unchanged behaviour)', function () {
      const profile = {
        autoGenerated: true,
        bounds: { minAngle: 0, maxAngle: 180 }
      };
      expect(isPlaceholderProfile(profile)).to.equal(true);
      expect(calibratedBounds(profile)).to.equal(null);
    });
  });
});
