/**
 * Operator ruling (2026-08-22): "Mark as Calibrated should be available for
 * ALL part types in this form." The stamp endpoint already accepted any part
 * WITH a profile, but profile auto-creation returned null for every
 * non-motion type (webcam, microphone, speaker, sensor, light), so those
 * parts had no profile, and the calibration page hid the stamp for them.
 *
 * Pinned here: a non-motion part gets a minimal 'device' profile, the stamp
 * round-trips on it, and motion endpoints still refuse to drive it.
 */

import { expect } from 'chai';
import request from 'supertest';
import express from 'express';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const APP_ROOT = path.resolve(__dirname, '..', '..');

const DEVICE_PART_ID = 987657; // synthetic microphone

describe('Calibrated stamp on non-motion part types (device profiles)', function () {
  this.timeout(20000);

  let app;
  let partsPath;
  const savedFiles = new Map();

  before(async function () {
    const { readConfig } = await import('../../services/configService.js');
    const cfg = await readConfig();
    const characterId = cfg && cfg.selectedCharacter;
    if (characterId == null) this.skip();

    partsPath = path.join(APP_ROOT, 'data', `character-${characterId}`, 'parts.json');
    for (const f of [partsPath, path.join(APP_ROOT, 'data', 'calibration_profiles.json')]) {
      try { savedFiles.set(f, await fs.readFile(f, 'utf8')); } catch (_) { savedFiles.set(f, null); }
    }

    const parts = JSON.parse(savedFiles.get(partsPath) || '[]');
    parts.push({
      id: String(DEVICE_PART_ID),
      name: 'Device Stamp Test Mic (synthetic)',
      type: 'microphone',
      enabled: true,
      config: {}
    });
    await fs.writeFile(partsPath, JSON.stringify(parts, null, 2), 'utf8');

    const { default: router } = await import('../../server/calibration/router.js');
    app = express();
    app.use('/api/calibration', router);
  });

  after(async function () {
    for (const [f, content] of savedFiles) {
      try {
        if (content !== null) await fs.writeFile(f, content, 'utf8');
        else await fs.rm(f, { force: true });
      } catch (_) { /* best effort */ }
    }
  });

  it('auto-creates a minimal device profile instead of returning nothing', async function () {
    const res = await request(app)
      .get(`/api/calibration/${DEVICE_PART_ID}/profile`)
      .expect(200);
    const profile = res.body.profile || res.body;
    expect(profile.capability.kind).to.equal('device');
    expect(profile.bounds, 'a device has no motion window').to.equal(null);
    expect(profile.autoGenerated).to.equal(true);
  });

  it('the Calibrated stamp round-trips on a device part', async function () {
    let res = await request(app)
      .post(`/api/calibration/${DEVICE_PART_ID}/calibrated`)
      .send({ calibrated: true })
      .expect(200);
    expect(res.body.success).to.equal(true);
    expect(res.body.calibrated).to.equal(true);

    res = await request(app)
      .post(`/api/calibration/${DEVICE_PART_ID}/calibrated`)
      .send({ calibrated: false })
      .expect(200);
    expect(res.body.calibrated).to.equal(false);
  });

  it('motion endpoints still refuse to drive a device', async function () {
    const res = await request(app)
      .post(`/api/calibration/${DEVICE_PART_ID}/goto`)
      .send({ angle: 90 });
    expect(res.status, 'a mic must never be drivable').to.be.oneOf([400, 500]);
    expect(res.body.success).to.equal(false);
  });
});
