/**
 * resolveDriveWindow — an uncalibrated absolute servo is DRIVEN through its
 * full span, never refused (doctrine change 2026-09-07). Measured calibration
 * still wins when it exists; a caller's preferred window beats the placeholder.
 *
 * Uses a JsonCalibrationStore on a scratch file through the `store` test seam,
 * so the node's real calibration_profiles.json is never touched.
 */
import { expect } from 'chai';
import fs from 'fs/promises';
import path from 'path';
import os from 'os';

describe('resolveDriveWindow — uncalibrated servos drive, not refuse', function () {
  this.timeout(10000);

  const CID = 9042;
  let tmpDir;
  let store;
  let mod;

  before(async function () {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'mb-drive-window-'));
    const file = path.join(tmpDir, 'calibration_profiles.json');
    await fs.writeFile(file, JSON.stringify({
      [`${CID}:1`]: { partId: 1, characterId: CID, capability: { kind: 'absolute-servo' }, bounds: { minAngle: 33, maxAngle: 98 }, autoGenerated: false, version: 1 },
      [`${CID}:2`]: { partId: 2, characterId: CID, capability: { kind: 'absolute-servo' }, bounds: { minAngle: 0, maxAngle: 180 }, autoGenerated: true, version: 1 },
      [`${CID}:4`]: { partId: 4, characterId: CID, capability: { kind: 'absolute-servo' }, bounds: { minAngle: 90, maxAngle: 90 }, autoGenerated: false, version: 1 }
    }, null, 2));
    const storeMod = await import('../../server/calibration/store.js');
    store = new storeMod.JsonCalibrationStore(file);
    mod = await import('../../services/hardwareService/driveWindow.js');
    mod._resetAnnouncements();
  });

  after(async function () {
    try { await fs.rm(tmpDir, { recursive: true, force: true }); } catch (_) { /* best effort */ }
  });

  it('uses the measured window when the profile is real', async function () {
    const win = await mod.resolveDriveWindow(CID, { id: 1, name: 'Jaw', config: {} }, { store, quiet: true });
    expect(win).to.include({ minAngle: 33, maxAngle: 98, calibrated: true, source: 'calibration' });
  });

  it('prefers the caller window over the placeholder span when uncalibrated', async function () {
    const win = await mod.resolveDriveWindow(CID, { id: 2, name: 'Neck', config: {} },
      { store, preferred: { minAngle: 60, maxAngle: 130 }, preferredSource: 'jaw-config', quiet: true });
    expect(win).to.include({ minAngle: 60, maxAngle: 130, calibrated: false, source: 'jaw-config' });
  });

  it('falls back to the placeholder span, then the full mechanical span', async function () {
    const placeholder = await mod.resolveDriveWindow(CID, { id: 2, name: 'Neck', config: {} }, { store, quiet: true });
    expect(placeholder).to.include({ minAngle: 0, maxAngle: 180, calibrated: false, source: 'placeholder-span' });

    const none = await mod.resolveDriveWindow(CID, { id: 3, name: 'Eye', config: { rotationRangeDeg: 270 } }, { store, quiet: true });
    expect(none).to.include({ minAngle: 0, maxAngle: 270, calibrated: false, source: 'full-span' });
  });

  it('treats a degenerate (pinned) window as uncalibrated rather than freezing the part', async function () {
    const win = await mod.resolveDriveWindow(CID, { id: 4, name: 'Pinned', config: {} }, { store, quiet: true });
    expect(win.calibrated).to.equal(false);
    expect(win.maxAngle).to.be.greaterThan(win.minAngle);
  });

  it('never returns null or a degenerate window for an absolute servo', async function () {
    const win = await mod.resolveDriveWindow(CID, { id: 77, name: 'Unknown', config: {} }, { store, quiet: true });
    expect(win).to.be.an('object');
    expect(win.maxAngle).to.be.greaterThan(win.minAngle);
  });
});
